/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables;


import com.santika.simrs.jooq.kepegawaian.Kepegawaian;
import com.santika.simrs.jooq.kepegawaian.Keys;
import com.santika.simrs.jooq.kepegawaian.tables.records.BidangPegawaiRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BidangPegawai extends TableImpl<BidangPegawaiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>KEPEGAWAIAN.BIDANG_PEGAWAI</code>
     */
    public static final BidangPegawai BIDANG_PEGAWAI = new BidangPegawai();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BidangPegawaiRecord> getRecordType() {
        return BidangPegawaiRecord.class;
    }

    /**
     * The column <code>KEPEGAWAIAN.BIDANG_PEGAWAI.ID</code>.
     */
    public final TableField<BidangPegawaiRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>KEPEGAWAIAN.BIDANG_PEGAWAI.KODE_BIDANG</code>.
     */
    public final TableField<BidangPegawaiRecord, String> KODE_BIDANG = createField(DSL.name("KODE_BIDANG"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.BIDANG_PEGAWAI.NAMA_BIDANG</code>.
     */
    public final TableField<BidangPegawaiRecord, String> NAMA_BIDANG = createField(DSL.name("NAMA_BIDANG"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.BIDANG_PEGAWAI.DELETED_AT</code>.
     */
    public final TableField<BidangPegawaiRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.BIDANG_PEGAWAI.CREATED_AT</code>.
     */
    public final TableField<BidangPegawaiRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.BIDANG_PEGAWAI.UPDATED_AT</code>.
     */
    public final TableField<BidangPegawaiRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private BidangPegawai(Name alias, Table<BidangPegawaiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BidangPegawai(Name alias, Table<BidangPegawaiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.BIDANG_PEGAWAI</code> table reference
     */
    public BidangPegawai(String alias) {
        this(DSL.name(alias), BIDANG_PEGAWAI);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.BIDANG_PEGAWAI</code> table reference
     */
    public BidangPegawai(Name alias) {
        this(alias, BIDANG_PEGAWAI);
    }

    /**
     * Create a <code>KEPEGAWAIAN.BIDANG_PEGAWAI</code> table reference
     */
    public BidangPegawai() {
        this(DSL.name("BIDANG_PEGAWAI"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public UniqueKey<BidangPegawaiRecord> getPrimaryKey() {
        return Keys.PK_BIDANG_PEGAWAI;
    }

    @Override
    public BidangPegawai as(String alias) {
        return new BidangPegawai(DSL.name(alias), this);
    }

    @Override
    public BidangPegawai as(Name alias) {
        return new BidangPegawai(alias, this);
    }

    @Override
    public BidangPegawai as(Table<?> alias) {
        return new BidangPegawai(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BidangPegawai rename(String name) {
        return new BidangPegawai(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BidangPegawai rename(Name name) {
        return new BidangPegawai(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BidangPegawai rename(Table<?> name) {
        return new BidangPegawai(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BidangPegawai where(Condition condition) {
        return new BidangPegawai(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BidangPegawai where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BidangPegawai where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BidangPegawai where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BidangPegawai where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BidangPegawai where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BidangPegawai where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BidangPegawai where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BidangPegawai whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BidangPegawai whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
