/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables;


import com.santika.simrs.jooq.kepegawaian.Kepegawaian;
import com.santika.simrs.jooq.kepegawaian.Keys;
import com.santika.simrs.jooq.kepegawaian.tables.records.DaruratPegawaiRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DaruratPegawai extends TableImpl<DaruratPegawaiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>KEPEGAWAIAN.DARURAT_PEGAWAI</code>
     */
    public static final DaruratPegawai DARURAT_PEGAWAI = new DaruratPegawai();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DaruratPegawaiRecord> getRecordType() {
        return DaruratPegawaiRecord.class;
    }

    /**
     * The column <code>KEPEGAWAIAN.DARURAT_PEGAWAI.ID</code>.
     */
    public final TableField<DaruratPegawaiRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DARURAT_PEGAWAI.KODE_EMERGENCY</code>.
     */
    public final TableField<DaruratPegawaiRecord, String> KODE_EMERGENCY = createField(DSL.name("KODE_EMERGENCY"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DARURAT_PEGAWAI.NAMA_EMERGENCY</code>.
     */
    public final TableField<DaruratPegawaiRecord, String> NAMA_EMERGENCY = createField(DSL.name("NAMA_EMERGENCY"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DARURAT_PEGAWAI.DELETED_AT</code>.
     */
    public final TableField<DaruratPegawaiRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DARURAT_PEGAWAI.CREATED_AT</code>.
     */
    public final TableField<DaruratPegawaiRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DARURAT_PEGAWAI.UPDATED_AT</code>.
     */
    public final TableField<DaruratPegawaiRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private DaruratPegawai(Name alias, Table<DaruratPegawaiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DaruratPegawai(Name alias, Table<DaruratPegawaiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.DARURAT_PEGAWAI</code> table
     * reference
     */
    public DaruratPegawai(String alias) {
        this(DSL.name(alias), DARURAT_PEGAWAI);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.DARURAT_PEGAWAI</code> table
     * reference
     */
    public DaruratPegawai(Name alias) {
        this(alias, DARURAT_PEGAWAI);
    }

    /**
     * Create a <code>KEPEGAWAIAN.DARURAT_PEGAWAI</code> table reference
     */
    public DaruratPegawai() {
        this(DSL.name("DARURAT_PEGAWAI"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public UniqueKey<DaruratPegawaiRecord> getPrimaryKey() {
        return Keys.PK_DARURAT_PEGAWAI;
    }

    @Override
    public DaruratPegawai as(String alias) {
        return new DaruratPegawai(DSL.name(alias), this);
    }

    @Override
    public DaruratPegawai as(Name alias) {
        return new DaruratPegawai(alias, this);
    }

    @Override
    public DaruratPegawai as(Table<?> alias) {
        return new DaruratPegawai(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DaruratPegawai rename(String name) {
        return new DaruratPegawai(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DaruratPegawai rename(Name name) {
        return new DaruratPegawai(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DaruratPegawai rename(Table<?> name) {
        return new DaruratPegawai(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DaruratPegawai where(Condition condition) {
        return new DaruratPegawai(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DaruratPegawai where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DaruratPegawai where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DaruratPegawai where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DaruratPegawai where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DaruratPegawai where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DaruratPegawai where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DaruratPegawai where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DaruratPegawai whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DaruratPegawai whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
