/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables;


import com.santika.simrs.jooq.kepegawaian.Kepegawaian;
import com.santika.simrs.jooq.kepegawaian.Keys;
import com.santika.simrs.jooq.kepegawaian.tables.records.DepartemenPegawaiRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DepartemenPegawai extends TableImpl<DepartemenPegawaiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>KEPEGAWAIAN.DEPARTEMEN_PEGAWAI</code>
     */
    public static final DepartemenPegawai DEPARTEMEN_PEGAWAI = new DepartemenPegawai();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DepartemenPegawaiRecord> getRecordType() {
        return DepartemenPegawaiRecord.class;
    }

    /**
     * The column <code>KEPEGAWAIAN.DEPARTEMEN_PEGAWAI.ID</code>.
     */
    public final TableField<DepartemenPegawaiRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DEPARTEMEN_PEGAWAI.KODE_DEPARTEMEN</code>.
     */
    public final TableField<DepartemenPegawaiRecord, String> KODE_DEPARTEMEN = createField(DSL.name("KODE_DEPARTEMEN"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DEPARTEMEN_PEGAWAI.NAMA_DEPARTEMEN</code>.
     */
    public final TableField<DepartemenPegawaiRecord, String> NAMA_DEPARTEMEN = createField(DSL.name("NAMA_DEPARTEMEN"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DEPARTEMEN_PEGAWAI.DELETED_AT</code>.
     */
    public final TableField<DepartemenPegawaiRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DEPARTEMEN_PEGAWAI.CREATED_AT</code>.
     */
    public final TableField<DepartemenPegawaiRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DEPARTEMEN_PEGAWAI.UPDATED_AT</code>.
     */
    public final TableField<DepartemenPegawaiRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private DepartemenPegawai(Name alias, Table<DepartemenPegawaiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DepartemenPegawai(Name alias, Table<DepartemenPegawaiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.DEPARTEMEN_PEGAWAI</code> table
     * reference
     */
    public DepartemenPegawai(String alias) {
        this(DSL.name(alias), DEPARTEMEN_PEGAWAI);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.DEPARTEMEN_PEGAWAI</code> table
     * reference
     */
    public DepartemenPegawai(Name alias) {
        this(alias, DEPARTEMEN_PEGAWAI);
    }

    /**
     * Create a <code>KEPEGAWAIAN.DEPARTEMEN_PEGAWAI</code> table reference
     */
    public DepartemenPegawai() {
        this(DSL.name("DEPARTEMEN_PEGAWAI"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public UniqueKey<DepartemenPegawaiRecord> getPrimaryKey() {
        return Keys.PK_DEPARTEMEN_PEGAWAI;
    }

    @Override
    public DepartemenPegawai as(String alias) {
        return new DepartemenPegawai(DSL.name(alias), this);
    }

    @Override
    public DepartemenPegawai as(Name alias) {
        return new DepartemenPegawai(alias, this);
    }

    @Override
    public DepartemenPegawai as(Table<?> alias) {
        return new DepartemenPegawai(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DepartemenPegawai rename(String name) {
        return new DepartemenPegawai(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DepartemenPegawai rename(Name name) {
        return new DepartemenPegawai(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DepartemenPegawai rename(Table<?> name) {
        return new DepartemenPegawai(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DepartemenPegawai where(Condition condition) {
        return new DepartemenPegawai(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DepartemenPegawai where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DepartemenPegawai where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DepartemenPegawai where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DepartemenPegawai where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DepartemenPegawai where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DepartemenPegawai where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DepartemenPegawai where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DepartemenPegawai whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DepartemenPegawai whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
