/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables;


import com.santika.simrs.jooq.kepegawaian.Kepegawaian;
import com.santika.simrs.jooq.kepegawaian.Keys;
import com.santika.simrs.jooq.kepegawaian.tables.Pegawai.PegawaiPath;
import com.santika.simrs.jooq.kepegawaian.tables.Spesialis.SpesialisPath;
import com.santika.simrs.jooq.kepegawaian.tables.records.DokterRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Dokter extends TableImpl<DokterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>KEPEGAWAIAN.DOKTER</code>
     */
    public static final Dokter DOKTER = new Dokter();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DokterRecord> getRecordType() {
        return DokterRecord.class;
    }

    /**
     * The column <code>KEPEGAWAIAN.DOKTER.ID</code>.
     */
    public final TableField<DokterRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKTER.PEGAWAI_ID</code>.
     */
    public final TableField<DokterRecord, UUID> PEGAWAI_ID = createField(DSL.name("PEGAWAI_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKTER.NAMA_DOKTER</code>.
     */
    public final TableField<DokterRecord, String> NAMA_DOKTER = createField(DSL.name("NAMA_DOKTER"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKTER.NIP</code>.
     */
    public final TableField<DokterRecord, String> NIP = createField(DSL.name("NIP"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKTER.TELEPHONE_DOKTER</code>.
     */
    public final TableField<DokterRecord, String> TELEPHONE_DOKTER = createField(DSL.name("TELEPHONE_DOKTER"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKTER.EMAIL_DOKTER</code>.
     */
    public final TableField<DokterRecord, String> EMAIL_DOKTER = createField(DSL.name("EMAIL_DOKTER"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKTER.SPESIALIS_ID</code>.
     */
    public final TableField<DokterRecord, UUID> SPESIALIS_ID = createField(DSL.name("SPESIALIS_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKTER.ALUMNI</code>.
     */
    public final TableField<DokterRecord, String> ALUMNI = createField(DSL.name("ALUMNI"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKTER.NO_IJIN_PRAKTEK</code>.
     */
    public final TableField<DokterRecord, String> NO_IJIN_PRAKTEK = createField(DSL.name("NO_IJIN_PRAKTEK"), SQLDataType.VARCHAR(120), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKTER.DOKUMEN_IJIN_PRAKTIK_ID</code>.
     */
    public final TableField<DokterRecord, UUID> DOKUMEN_IJIN_PRAKTIK_ID = createField(DSL.name("DOKUMEN_IJIN_PRAKTIK_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKTER.IS_ACTIVE</code>.
     */
    public final TableField<DokterRecord, Boolean> IS_ACTIVE = createField(DSL.name("IS_ACTIVE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("TRUE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKTER.DELETED_AT</code>.
     */
    public final TableField<DokterRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKTER.CREATED_AT</code>.
     */
    public final TableField<DokterRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKTER.UPDATED_AT</code>.
     */
    public final TableField<DokterRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private Dokter(Name alias, Table<DokterRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Dokter(Name alias, Table<DokterRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.DOKTER</code> table reference
     */
    public Dokter(String alias) {
        this(DSL.name(alias), DOKTER);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.DOKTER</code> table reference
     */
    public Dokter(Name alias) {
        this(alias, DOKTER);
    }

    /**
     * Create a <code>KEPEGAWAIAN.DOKTER</code> table reference
     */
    public Dokter() {
        this(DSL.name("DOKTER"), null);
    }

    public <O extends Record> Dokter(Table<O> path, ForeignKey<O, DokterRecord> childPath, InverseForeignKey<O, DokterRecord> parentPath) {
        super(path, childPath, parentPath, DOKTER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DokterPath extends Dokter implements Path<DokterRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DokterPath(Table<O> path, ForeignKey<O, DokterRecord> childPath, InverseForeignKey<O, DokterRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DokterPath(Name alias, Table<DokterRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DokterPath as(String alias) {
            return new DokterPath(DSL.name(alias), this);
        }

        @Override
        public DokterPath as(Name alias) {
            return new DokterPath(alias, this);
        }

        @Override
        public DokterPath as(Table<?> alias) {
            return new DokterPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public UniqueKey<DokterRecord> getPrimaryKey() {
        return Keys.PK_DOKTER;
    }

    @Override
    public List<ForeignKey<DokterRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_DOKTER_PEGAWAI, Keys.FK_DOKTER_SPESIALIS);
    }

    private transient PegawaiPath _pegawai;

    /**
     * Get the implicit join path to the <code>KEPEGAWAIAN.PEGAWAI</code> table.
     */
    public PegawaiPath pegawai() {
        if (_pegawai == null)
            _pegawai = new PegawaiPath(this, Keys.FK_DOKTER_PEGAWAI, null);

        return _pegawai;
    }

    private transient SpesialisPath _spesialis;

    /**
     * Get the implicit join path to the <code>KEPEGAWAIAN.SPESIALIS</code>
     * table.
     */
    public SpesialisPath spesialis() {
        if (_spesialis == null)
            _spesialis = new SpesialisPath(this, Keys.FK_DOKTER_SPESIALIS, null);

        return _spesialis;
    }

    @Override
    public Dokter as(String alias) {
        return new Dokter(DSL.name(alias), this);
    }

    @Override
    public Dokter as(Name alias) {
        return new Dokter(alias, this);
    }

    @Override
    public Dokter as(Table<?> alias) {
        return new Dokter(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Dokter rename(String name) {
        return new Dokter(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dokter rename(Name name) {
        return new Dokter(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dokter rename(Table<?> name) {
        return new Dokter(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dokter where(Condition condition) {
        return new Dokter(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dokter where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dokter where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dokter where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dokter where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dokter where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dokter where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dokter where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dokter whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dokter whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
