/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables;


import com.santika.simrs.jooq.kepegawaian.Kepegawaian;
import com.santika.simrs.jooq.kepegawaian.Keys;
import com.santika.simrs.jooq.kepegawaian.tables.Pegawai.PegawaiPath;
import com.santika.simrs.jooq.kepegawaian.tables.records.DokumenPegawaiRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DokumenPegawai extends TableImpl<DokumenPegawaiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI</code>
     */
    public static final DokumenPegawai DOKUMEN_PEGAWAI = new DokumenPegawai();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DokumenPegawaiRecord> getRecordType() {
        return DokumenPegawaiRecord.class;
    }

    /**
     * The column <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.ID</code>.
     */
    public final TableField<DokumenPegawaiRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.PEGAWAI_ID</code>.
     */
    public final TableField<DokumenPegawaiRecord, UUID> PEGAWAI_ID = createField(DSL.name("PEGAWAI_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.NAMA_DOKUMEN</code>.
     */
    public final TableField<DokumenPegawaiRecord, String> NAMA_DOKUMEN = createField(DSL.name("NAMA_DOKUMEN"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.FILE_ID</code>.
     */
    public final TableField<DokumenPegawaiRecord, UUID> FILE_ID = createField(DSL.name("FILE_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.IS_ACTIVE</code>.
     */
    public final TableField<DokumenPegawaiRecord, Boolean> IS_ACTIVE = createField(DSL.name("IS_ACTIVE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("TRUE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.DELETED_AT</code>.
     */
    public final TableField<DokumenPegawaiRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.CREATED_AT</code>.
     */
    public final TableField<DokumenPegawaiRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.UPDATED_AT</code>.
     */
    public final TableField<DokumenPegawaiRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private DokumenPegawai(Name alias, Table<DokumenPegawaiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DokumenPegawai(Name alias, Table<DokumenPegawaiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI</code> table
     * reference
     */
    public DokumenPegawai(String alias) {
        this(DSL.name(alias), DOKUMEN_PEGAWAI);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI</code> table
     * reference
     */
    public DokumenPegawai(Name alias) {
        this(alias, DOKUMEN_PEGAWAI);
    }

    /**
     * Create a <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI</code> table reference
     */
    public DokumenPegawai() {
        this(DSL.name("DOKUMEN_PEGAWAI"), null);
    }

    public <O extends Record> DokumenPegawai(Table<O> path, ForeignKey<O, DokumenPegawaiRecord> childPath, InverseForeignKey<O, DokumenPegawaiRecord> parentPath) {
        super(path, childPath, parentPath, DOKUMEN_PEGAWAI);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DokumenPegawaiPath extends DokumenPegawai implements Path<DokumenPegawaiRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DokumenPegawaiPath(Table<O> path, ForeignKey<O, DokumenPegawaiRecord> childPath, InverseForeignKey<O, DokumenPegawaiRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DokumenPegawaiPath(Name alias, Table<DokumenPegawaiRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DokumenPegawaiPath as(String alias) {
            return new DokumenPegawaiPath(DSL.name(alias), this);
        }

        @Override
        public DokumenPegawaiPath as(Name alias) {
            return new DokumenPegawaiPath(alias, this);
        }

        @Override
        public DokumenPegawaiPath as(Table<?> alias) {
            return new DokumenPegawaiPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public UniqueKey<DokumenPegawaiRecord> getPrimaryKey() {
        return Keys.PK_DOKUMEN_PEGAWAI;
    }

    @Override
    public List<ForeignKey<DokumenPegawaiRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_DOKUMEN_PEGAWAI_PEGAWAI);
    }

    private transient PegawaiPath _pegawai;

    /**
     * Get the implicit join path to the <code>KEPEGAWAIAN.PEGAWAI</code> table.
     */
    public PegawaiPath pegawai() {
        if (_pegawai == null)
            _pegawai = new PegawaiPath(this, Keys.FK_DOKUMEN_PEGAWAI_PEGAWAI, null);

        return _pegawai;
    }

    @Override
    public DokumenPegawai as(String alias) {
        return new DokumenPegawai(DSL.name(alias), this);
    }

    @Override
    public DokumenPegawai as(Name alias) {
        return new DokumenPegawai(alias, this);
    }

    @Override
    public DokumenPegawai as(Table<?> alias) {
        return new DokumenPegawai(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DokumenPegawai rename(String name) {
        return new DokumenPegawai(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DokumenPegawai rename(Name name) {
        return new DokumenPegawai(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DokumenPegawai rename(Table<?> name) {
        return new DokumenPegawai(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DokumenPegawai where(Condition condition) {
        return new DokumenPegawai(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DokumenPegawai where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DokumenPegawai where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DokumenPegawai where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DokumenPegawai where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DokumenPegawai where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DokumenPegawai where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DokumenPegawai where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DokumenPegawai whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DokumenPegawai whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
