/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables;


import com.santika.simrs.jooq.kepegawaian.Kepegawaian;
import com.santika.simrs.jooq.kepegawaian.Keys;
import com.santika.simrs.jooq.kepegawaian.tables.records.KelompokPegawaiRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class KelompokPegawai extends TableImpl<KelompokPegawaiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>KEPEGAWAIAN.KELOMPOK_PEGAWAI</code>
     */
    public static final KelompokPegawai KELOMPOK_PEGAWAI = new KelompokPegawai();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<KelompokPegawaiRecord> getRecordType() {
        return KelompokPegawaiRecord.class;
    }

    /**
     * The column <code>KEPEGAWAIAN.KELOMPOK_PEGAWAI.ID</code>.
     */
    public final TableField<KelompokPegawaiRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>KEPEGAWAIAN.KELOMPOK_PEGAWAI.KODE_KELOMPOK</code>.
     */
    public final TableField<KelompokPegawaiRecord, String> KODE_KELOMPOK = createField(DSL.name("KODE_KELOMPOK"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.KELOMPOK_PEGAWAI.NAMA_KELOMPOK</code>.
     */
    public final TableField<KelompokPegawaiRecord, String> NAMA_KELOMPOK = createField(DSL.name("NAMA_KELOMPOK"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.KELOMPOK_PEGAWAI.DELETED_AT</code>.
     */
    public final TableField<KelompokPegawaiRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.KELOMPOK_PEGAWAI.CREATED_AT</code>.
     */
    public final TableField<KelompokPegawaiRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.KELOMPOK_PEGAWAI.UPDATED_AT</code>.
     */
    public final TableField<KelompokPegawaiRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private KelompokPegawai(Name alias, Table<KelompokPegawaiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private KelompokPegawai(Name alias, Table<KelompokPegawaiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.KELOMPOK_PEGAWAI</code> table
     * reference
     */
    public KelompokPegawai(String alias) {
        this(DSL.name(alias), KELOMPOK_PEGAWAI);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.KELOMPOK_PEGAWAI</code> table
     * reference
     */
    public KelompokPegawai(Name alias) {
        this(alias, KELOMPOK_PEGAWAI);
    }

    /**
     * Create a <code>KEPEGAWAIAN.KELOMPOK_PEGAWAI</code> table reference
     */
    public KelompokPegawai() {
        this(DSL.name("KELOMPOK_PEGAWAI"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public UniqueKey<KelompokPegawaiRecord> getPrimaryKey() {
        return Keys.PK_KELOMPOK_PEGAWAI;
    }

    @Override
    public KelompokPegawai as(String alias) {
        return new KelompokPegawai(DSL.name(alias), this);
    }

    @Override
    public KelompokPegawai as(Name alias) {
        return new KelompokPegawai(alias, this);
    }

    @Override
    public KelompokPegawai as(Table<?> alias) {
        return new KelompokPegawai(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public KelompokPegawai rename(String name) {
        return new KelompokPegawai(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public KelompokPegawai rename(Name name) {
        return new KelompokPegawai(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public KelompokPegawai rename(Table<?> name) {
        return new KelompokPegawai(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KelompokPegawai where(Condition condition) {
        return new KelompokPegawai(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KelompokPegawai where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KelompokPegawai where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KelompokPegawai where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KelompokPegawai where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KelompokPegawai where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KelompokPegawai where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public KelompokPegawai where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KelompokPegawai whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public KelompokPegawai whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
