/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables;


import com.santika.simrs.jooq.kepegawaian.Kepegawaian;
import com.santika.simrs.jooq.kepegawaian.Keys;
import com.santika.simrs.jooq.kepegawaian.tables.Dokter.DokterPath;
import com.santika.simrs.jooq.kepegawaian.tables.DokumenPegawai.DokumenPegawaiPath;
import com.santika.simrs.jooq.kepegawaian.tables.records.PegawaiRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Pegawai extends TableImpl<PegawaiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>KEPEGAWAIAN.PEGAWAI</code>
     */
    public static final Pegawai PEGAWAI = new Pegawai();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PegawaiRecord> getRecordType() {
        return PegawaiRecord.class;
    }

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.ID</code>.
     */
    public final TableField<PegawaiRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.NAMA</code>.
     */
    public final TableField<PegawaiRecord, String> NAMA = createField(DSL.name("NAMA"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.NIP</code>.
     */
    public final TableField<PegawaiRecord, String> NIP = createField(DSL.name("NIP"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.JENIS_IDENTITAS</code>.
     */
    public final TableField<PegawaiRecord, String> JENIS_IDENTITAS = createField(DSL.name("JENIS_IDENTITAS"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.IDENTITAS_LAIN</code>.
     */
    public final TableField<PegawaiRecord, String> IDENTITAS_LAIN = createField(DSL.name("IDENTITAS_LAIN"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.NO_IDENTITAS</code>.
     */
    public final TableField<PegawaiRecord, String> NO_IDENTITAS = createField(DSL.name("NO_IDENTITAS"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.KELAMIN</code>.
     */
    public final TableField<PegawaiRecord, String> KELAMIN = createField(DSL.name("KELAMIN"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.JABATAN</code>.
     */
    public final TableField<PegawaiRecord, String> JABATAN = createField(DSL.name("JABATAN"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.TELEPHONE</code>.
     */
    public final TableField<PegawaiRecord, String> TELEPHONE = createField(DSL.name("TELEPHONE"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.EMAIL</code>.
     */
    public final TableField<PegawaiRecord, String> EMAIL = createField(DSL.name("EMAIL"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.JENJANG_JABATAN</code>.
     */
    public final TableField<PegawaiRecord, String> JENJANG_JABATAN = createField(DSL.name("JENJANG_JABATAN"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.KELOMPOK_PEGAWAI_ID</code>.
     */
    public final TableField<PegawaiRecord, UUID> KELOMPOK_PEGAWAI_ID = createField(DSL.name("KELOMPOK_PEGAWAI_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.RESIKO_PEGAWAI_ID</code>.
     */
    public final TableField<PegawaiRecord, UUID> RESIKO_PEGAWAI_ID = createField(DSL.name("RESIKO_PEGAWAI_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.DARURAT_PEGAWAI_ID</code>.
     */
    public final TableField<PegawaiRecord, UUID> DARURAT_PEGAWAI_ID = createField(DSL.name("DARURAT_PEGAWAI_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.DEPARTEMEN_PEGAWAI_ID</code>.
     */
    public final TableField<PegawaiRecord, UUID> DEPARTEMEN_PEGAWAI_ID = createField(DSL.name("DEPARTEMEN_PEGAWAI_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.BIDANG_PEGAWAI_ID</code>.
     */
    public final TableField<PegawaiRecord, UUID> BIDANG_PEGAWAI_ID = createField(DSL.name("BIDANG_PEGAWAI_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.STATUS_PEGAWAI</code>.
     */
    public final TableField<PegawaiRecord, String> STATUS_PEGAWAI = createField(DSL.name("STATUS_PEGAWAI"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("'KONTRAK'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.VENDOR_TENAGA_LUAR_ID</code>.
     */
    public final TableField<PegawaiRecord, UUID> VENDOR_TENAGA_LUAR_ID = createField(DSL.name("VENDOR_TENAGA_LUAR_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.PENDIDIKAN</code>.
     */
    public final TableField<PegawaiRecord, String> PENDIDIKAN = createField(DSL.name("PENDIDIKAN"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.TEMPAT_LAHIR</code>.
     */
    public final TableField<PegawaiRecord, String> TEMPAT_LAHIR = createField(DSL.name("TEMPAT_LAHIR"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.TANGGAL_LAHIR</code>.
     */
    public final TableField<PegawaiRecord, LocalDate> TANGGAL_LAHIR = createField(DSL.name("TANGGAL_LAHIR"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.PROVINSI_ID</code>.
     */
    public final TableField<PegawaiRecord, UUID> PROVINSI_ID = createField(DSL.name("PROVINSI_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.KABUPATEN_ID</code>.
     */
    public final TableField<PegawaiRecord, UUID> KABUPATEN_ID = createField(DSL.name("KABUPATEN_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.KECAMATAN_ID</code>.
     */
    public final TableField<PegawaiRecord, UUID> KECAMATAN_ID = createField(DSL.name("KECAMATAN_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.KELURAHAN_ID</code>.
     */
    public final TableField<PegawaiRecord, UUID> KELURAHAN_ID = createField(DSL.name("KELURAHAN_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.ALAMAT</code>.
     */
    public final TableField<PegawaiRecord, String> ALAMAT = createField(DSL.name("ALAMAT"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.MULAI_BEKERJA</code>.
     */
    public final TableField<PegawaiRecord, LocalDate> MULAI_BEKERJA = createField(DSL.name("MULAI_BEKERJA"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.FOTO_ID</code>.
     */
    public final TableField<PegawaiRecord, UUID> FOTO_ID = createField(DSL.name("FOTO_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.IS_ACTIVE</code>.
     */
    public final TableField<PegawaiRecord, Boolean> IS_ACTIVE = createField(DSL.name("IS_ACTIVE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("TRUE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.DELETED_AT</code>.
     */
    public final TableField<PegawaiRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.CREATED_AT</code>.
     */
    public final TableField<PegawaiRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.PEGAWAI.UPDATED_AT</code>.
     */
    public final TableField<PegawaiRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private Pegawai(Name alias, Table<PegawaiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Pegawai(Name alias, Table<PegawaiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.PEGAWAI</code> table reference
     */
    public Pegawai(String alias) {
        this(DSL.name(alias), PEGAWAI);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.PEGAWAI</code> table reference
     */
    public Pegawai(Name alias) {
        this(alias, PEGAWAI);
    }

    /**
     * Create a <code>KEPEGAWAIAN.PEGAWAI</code> table reference
     */
    public Pegawai() {
        this(DSL.name("PEGAWAI"), null);
    }

    public <O extends Record> Pegawai(Table<O> path, ForeignKey<O, PegawaiRecord> childPath, InverseForeignKey<O, PegawaiRecord> parentPath) {
        super(path, childPath, parentPath, PEGAWAI);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PegawaiPath extends Pegawai implements Path<PegawaiRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PegawaiPath(Table<O> path, ForeignKey<O, PegawaiRecord> childPath, InverseForeignKey<O, PegawaiRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PegawaiPath(Name alias, Table<PegawaiRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PegawaiPath as(String alias) {
            return new PegawaiPath(DSL.name(alias), this);
        }

        @Override
        public PegawaiPath as(Name alias) {
            return new PegawaiPath(alias, this);
        }

        @Override
        public PegawaiPath as(Table<?> alias) {
            return new PegawaiPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public UniqueKey<PegawaiRecord> getPrimaryKey() {
        return Keys.PK_PEGAWAI;
    }

    private transient DokterPath _dokter;

    /**
     * Get the implicit to-many join path to the <code>KEPEGAWAIAN.DOKTER</code>
     * table
     */
    public DokterPath dokter() {
        if (_dokter == null)
            _dokter = new DokterPath(this, null, Keys.FK_DOKTER_PEGAWAI.getInverseKey());

        return _dokter;
    }

    private transient DokumenPegawaiPath _dokumenPegawai;

    /**
     * Get the implicit to-many join path to the
     * <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI</code> table
     */
    public DokumenPegawaiPath dokumenPegawai() {
        if (_dokumenPegawai == null)
            _dokumenPegawai = new DokumenPegawaiPath(this, null, Keys.FK_DOKUMEN_PEGAWAI_PEGAWAI.getInverseKey());

        return _dokumenPegawai;
    }

    @Override
    public Pegawai as(String alias) {
        return new Pegawai(DSL.name(alias), this);
    }

    @Override
    public Pegawai as(Name alias) {
        return new Pegawai(alias, this);
    }

    @Override
    public Pegawai as(Table<?> alias) {
        return new Pegawai(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Pegawai rename(String name) {
        return new Pegawai(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Pegawai rename(Name name) {
        return new Pegawai(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Pegawai rename(Table<?> name) {
        return new Pegawai(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pegawai where(Condition condition) {
        return new Pegawai(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pegawai where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pegawai where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pegawai where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pegawai where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pegawai where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pegawai where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pegawai where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pegawai whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pegawai whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
