/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables;


import com.santika.simrs.jooq.kepegawaian.Kepegawaian;
import com.santika.simrs.jooq.kepegawaian.Keys;
import com.santika.simrs.jooq.kepegawaian.tables.records.ResikoPegawaiRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ResikoPegawai extends TableImpl<ResikoPegawaiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>KEPEGAWAIAN.RESIKO_PEGAWAI</code>
     */
    public static final ResikoPegawai RESIKO_PEGAWAI = new ResikoPegawai();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResikoPegawaiRecord> getRecordType() {
        return ResikoPegawaiRecord.class;
    }

    /**
     * The column <code>KEPEGAWAIAN.RESIKO_PEGAWAI.ID</code>.
     */
    public final TableField<ResikoPegawaiRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>KEPEGAWAIAN.RESIKO_PEGAWAI.KODE_RESIKO</code>.
     */
    public final TableField<ResikoPegawaiRecord, String> KODE_RESIKO = createField(DSL.name("KODE_RESIKO"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.RESIKO_PEGAWAI.NAMA_RESIKO</code>.
     */
    public final TableField<ResikoPegawaiRecord, String> NAMA_RESIKO = createField(DSL.name("NAMA_RESIKO"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.RESIKO_PEGAWAI.DELETED_AT</code>.
     */
    public final TableField<ResikoPegawaiRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.RESIKO_PEGAWAI.CREATED_AT</code>.
     */
    public final TableField<ResikoPegawaiRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.RESIKO_PEGAWAI.UPDATED_AT</code>.
     */
    public final TableField<ResikoPegawaiRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private ResikoPegawai(Name alias, Table<ResikoPegawaiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ResikoPegawai(Name alias, Table<ResikoPegawaiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.RESIKO_PEGAWAI</code> table reference
     */
    public ResikoPegawai(String alias) {
        this(DSL.name(alias), RESIKO_PEGAWAI);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.RESIKO_PEGAWAI</code> table reference
     */
    public ResikoPegawai(Name alias) {
        this(alias, RESIKO_PEGAWAI);
    }

    /**
     * Create a <code>KEPEGAWAIAN.RESIKO_PEGAWAI</code> table reference
     */
    public ResikoPegawai() {
        this(DSL.name("RESIKO_PEGAWAI"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public UniqueKey<ResikoPegawaiRecord> getPrimaryKey() {
        return Keys.PK_RESIKO_PEGAWAI;
    }

    @Override
    public ResikoPegawai as(String alias) {
        return new ResikoPegawai(DSL.name(alias), this);
    }

    @Override
    public ResikoPegawai as(Name alias) {
        return new ResikoPegawai(alias, this);
    }

    @Override
    public ResikoPegawai as(Table<?> alias) {
        return new ResikoPegawai(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResikoPegawai rename(String name) {
        return new ResikoPegawai(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResikoPegawai rename(Name name) {
        return new ResikoPegawai(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResikoPegawai rename(Table<?> name) {
        return new ResikoPegawai(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResikoPegawai where(Condition condition) {
        return new ResikoPegawai(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResikoPegawai where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResikoPegawai where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResikoPegawai where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResikoPegawai where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResikoPegawai where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResikoPegawai where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ResikoPegawai where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResikoPegawai whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ResikoPegawai whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
