/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables;


import com.santika.simrs.jooq.kepegawaian.Kepegawaian;
import com.santika.simrs.jooq.kepegawaian.Keys;
import com.santika.simrs.jooq.kepegawaian.tables.Dokter.DokterPath;
import com.santika.simrs.jooq.kepegawaian.tables.records.SpesialisRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Spesialis extends TableImpl<SpesialisRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>KEPEGAWAIAN.SPESIALIS</code>
     */
    public static final Spesialis SPESIALIS = new Spesialis();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpesialisRecord> getRecordType() {
        return SpesialisRecord.class;
    }

    /**
     * The column <code>KEPEGAWAIAN.SPESIALIS.ID</code>.
     */
    public final TableField<SpesialisRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>KEPEGAWAIAN.SPESIALIS.KODE_SPESIALIS</code>.
     */
    public final TableField<SpesialisRecord, String> KODE_SPESIALIS = createField(DSL.name("KODE_SPESIALIS"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.SPESIALIS.NAMA_SPESIALIS</code>.
     */
    public final TableField<SpesialisRecord, String> NAMA_SPESIALIS = createField(DSL.name("NAMA_SPESIALIS"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.SPESIALIS.DELETED_AT</code>.
     */
    public final TableField<SpesialisRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.SPESIALIS.CREATED_AT</code>.
     */
    public final TableField<SpesialisRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.SPESIALIS.UPDATED_AT</code>.
     */
    public final TableField<SpesialisRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private Spesialis(Name alias, Table<SpesialisRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Spesialis(Name alias, Table<SpesialisRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.SPESIALIS</code> table reference
     */
    public Spesialis(String alias) {
        this(DSL.name(alias), SPESIALIS);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.SPESIALIS</code> table reference
     */
    public Spesialis(Name alias) {
        this(alias, SPESIALIS);
    }

    /**
     * Create a <code>KEPEGAWAIAN.SPESIALIS</code> table reference
     */
    public Spesialis() {
        this(DSL.name("SPESIALIS"), null);
    }

    public <O extends Record> Spesialis(Table<O> path, ForeignKey<O, SpesialisRecord> childPath, InverseForeignKey<O, SpesialisRecord> parentPath) {
        super(path, childPath, parentPath, SPESIALIS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SpesialisPath extends Spesialis implements Path<SpesialisRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SpesialisPath(Table<O> path, ForeignKey<O, SpesialisRecord> childPath, InverseForeignKey<O, SpesialisRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SpesialisPath(Name alias, Table<SpesialisRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SpesialisPath as(String alias) {
            return new SpesialisPath(DSL.name(alias), this);
        }

        @Override
        public SpesialisPath as(Name alias) {
            return new SpesialisPath(alias, this);
        }

        @Override
        public SpesialisPath as(Table<?> alias) {
            return new SpesialisPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public UniqueKey<SpesialisRecord> getPrimaryKey() {
        return Keys.PK_SPESIALIS;
    }

    private transient DokterPath _dokter;

    /**
     * Get the implicit to-many join path to the <code>KEPEGAWAIAN.DOKTER</code>
     * table
     */
    public DokterPath dokter() {
        if (_dokter == null)
            _dokter = new DokterPath(this, null, Keys.FK_DOKTER_SPESIALIS.getInverseKey());

        return _dokter;
    }

    @Override
    public Spesialis as(String alias) {
        return new Spesialis(DSL.name(alias), this);
    }

    @Override
    public Spesialis as(Name alias) {
        return new Spesialis(alias, this);
    }

    @Override
    public Spesialis as(Table<?> alias) {
        return new Spesialis(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Spesialis rename(String name) {
        return new Spesialis(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Spesialis rename(Name name) {
        return new Spesialis(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Spesialis rename(Table<?> name) {
        return new Spesialis(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Spesialis where(Condition condition) {
        return new Spesialis(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Spesialis where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Spesialis where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Spesialis where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Spesialis where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Spesialis where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Spesialis where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Spesialis where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Spesialis whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Spesialis whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
