/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables;


import com.santika.simrs.jooq.kepegawaian.Kepegawaian;
import com.santika.simrs.jooq.kepegawaian.Keys;
import com.santika.simrs.jooq.kepegawaian.tables.records.VendorTenagaLuarRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VendorTenagaLuar extends TableImpl<VendorTenagaLuarRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR</code>
     */
    public static final VendorTenagaLuar VENDOR_TENAGA_LUAR = new VendorTenagaLuar();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VendorTenagaLuarRecord> getRecordType() {
        return VendorTenagaLuarRecord.class;
    }

    /**
     * The column <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.ID</code>.
     */
    public final TableField<VendorTenagaLuarRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.NAMA_VENDOR</code>.
     */
    public final TableField<VendorTenagaLuarRecord, String> NAMA_VENDOR = createField(DSL.name("NAMA_VENDOR"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.ALAMAT_VENDOR</code>.
     */
    public final TableField<VendorTenagaLuarRecord, String> ALAMAT_VENDOR = createField(DSL.name("ALAMAT_VENDOR"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.BIDANG_VENDOR</code>.
     */
    public final TableField<VendorTenagaLuarRecord, String> BIDANG_VENDOR = createField(DSL.name("BIDANG_VENDOR"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.TELEPHONE_VENDOR</code>.
     */
    public final TableField<VendorTenagaLuarRecord, String> TELEPHONE_VENDOR = createField(DSL.name("TELEPHONE_VENDOR"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column
     * <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.NAMA_KONTAK_DARURAT</code>.
     */
    public final TableField<VendorTenagaLuarRecord, String> NAMA_KONTAK_DARURAT = createField(DSL.name("NAMA_KONTAK_DARURAT"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column
     * <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.KONTAK_DARURAT_VENDOR</code>.
     */
    public final TableField<VendorTenagaLuarRecord, String> KONTAK_DARURAT_VENDOR = createField(DSL.name("KONTAK_DARURAT_VENDOR"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.DELETED_AT</code>.
     */
    public final TableField<VendorTenagaLuarRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.CREATED_AT</code>.
     */
    public final TableField<VendorTenagaLuarRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.UPDATED_AT</code>.
     */
    public final TableField<VendorTenagaLuarRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private VendorTenagaLuar(Name alias, Table<VendorTenagaLuarRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VendorTenagaLuar(Name alias, Table<VendorTenagaLuarRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR</code> table
     * reference
     */
    public VendorTenagaLuar(String alias) {
        this(DSL.name(alias), VENDOR_TENAGA_LUAR);
    }

    /**
     * Create an aliased <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR</code> table
     * reference
     */
    public VendorTenagaLuar(Name alias) {
        this(alias, VENDOR_TENAGA_LUAR);
    }

    /**
     * Create a <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR</code> table reference
     */
    public VendorTenagaLuar() {
        this(DSL.name("VENDOR_TENAGA_LUAR"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kepegawaian.KEPEGAWAIAN;
    }

    @Override
    public UniqueKey<VendorTenagaLuarRecord> getPrimaryKey() {
        return Keys.PK_VENDOR_TENAGA_LUAR;
    }

    @Override
    public VendorTenagaLuar as(String alias) {
        return new VendorTenagaLuar(DSL.name(alias), this);
    }

    @Override
    public VendorTenagaLuar as(Name alias) {
        return new VendorTenagaLuar(alias, this);
    }

    @Override
    public VendorTenagaLuar as(Table<?> alias) {
        return new VendorTenagaLuar(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VendorTenagaLuar rename(String name) {
        return new VendorTenagaLuar(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VendorTenagaLuar rename(Name name) {
        return new VendorTenagaLuar(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VendorTenagaLuar rename(Table<?> name) {
        return new VendorTenagaLuar(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VendorTenagaLuar where(Condition condition) {
        return new VendorTenagaLuar(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VendorTenagaLuar where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VendorTenagaLuar where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VendorTenagaLuar where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VendorTenagaLuar where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VendorTenagaLuar where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VendorTenagaLuar where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VendorTenagaLuar where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VendorTenagaLuar whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VendorTenagaLuar whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
