/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian;


import com.santika.simrs.jooq.DefaultCatalog;
import com.santika.simrs.jooq.kepegawaian.tables.BidangPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.DaruratPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.DepartemenPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.Dokter;
import com.santika.simrs.jooq.kepegawaian.tables.DokumenPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.KelompokPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.Pegawai;
import com.santika.simrs.jooq.kepegawaian.tables.ResikoPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.Spesialis;
import com.santika.simrs.jooq.kepegawaian.tables.VendorTenagaLuar;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Kepegawaian extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>KEPEGAWAIAN</code>
     */
    public static final Kepegawaian KEPEGAWAIAN = new Kepegawaian();

    /**
     * The table <code>KEPEGAWAIAN.BIDANG_PEGAWAI</code>.
     */
    public final BidangPegawai BIDANG_PEGAWAI = BidangPegawai.BIDANG_PEGAWAI;

    /**
     * The table <code>KEPEGAWAIAN.DARURAT_PEGAWAI</code>.
     */
    public final DaruratPegawai DARURAT_PEGAWAI = DaruratPegawai.DARURAT_PEGAWAI;

    /**
     * The table <code>KEPEGAWAIAN.DEPARTEMEN_PEGAWAI</code>.
     */
    public final DepartemenPegawai DEPARTEMEN_PEGAWAI = DepartemenPegawai.DEPARTEMEN_PEGAWAI;

    /**
     * The table <code>KEPEGAWAIAN.DOKTER</code>.
     */
    public final Dokter DOKTER = Dokter.DOKTER;

    /**
     * The table <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI</code>.
     */
    public final DokumenPegawai DOKUMEN_PEGAWAI = DokumenPegawai.DOKUMEN_PEGAWAI;

    /**
     * The table <code>KEPEGAWAIAN.KELOMPOK_PEGAWAI</code>.
     */
    public final KelompokPegawai KELOMPOK_PEGAWAI = KelompokPegawai.KELOMPOK_PEGAWAI;

    /**
     * The table <code>KEPEGAWAIAN.PEGAWAI</code>.
     */
    public final Pegawai PEGAWAI = Pegawai.PEGAWAI;

    /**
     * The table <code>KEPEGAWAIAN.RESIKO_PEGAWAI</code>.
     */
    public final ResikoPegawai RESIKO_PEGAWAI = ResikoPegawai.RESIKO_PEGAWAI;

    /**
     * The table <code>KEPEGAWAIAN.SPESIALIS</code>.
     */
    public final Spesialis SPESIALIS = Spesialis.SPESIALIS;

    /**
     * The table <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR</code>.
     */
    public final VendorTenagaLuar VENDOR_TENAGA_LUAR = VendorTenagaLuar.VENDOR_TENAGA_LUAR;

    /**
     * No further instances allowed
     */
    private Kepegawaian() {
        super("KEPEGAWAIAN", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            BidangPegawai.BIDANG_PEGAWAI,
            DaruratPegawai.DARURAT_PEGAWAI,
            DepartemenPegawai.DEPARTEMEN_PEGAWAI,
            Dokter.DOKTER,
            DokumenPegawai.DOKUMEN_PEGAWAI,
            KelompokPegawai.KELOMPOK_PEGAWAI,
            Pegawai.PEGAWAI,
            ResikoPegawai.RESIKO_PEGAWAI,
            Spesialis.SPESIALIS,
            VendorTenagaLuar.VENDOR_TENAGA_LUAR
        );
    }
}
