/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian;


import com.santika.simrs.jooq.kepegawaian.tables.BidangPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.DaruratPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.DepartemenPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.Dokter;
import com.santika.simrs.jooq.kepegawaian.tables.DokumenPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.KelompokPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.Pegawai;
import com.santika.simrs.jooq.kepegawaian.tables.ResikoPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.Spesialis;
import com.santika.simrs.jooq.kepegawaian.tables.VendorTenagaLuar;
import com.santika.simrs.jooq.kepegawaian.tables.records.BidangPegawaiRecord;
import com.santika.simrs.jooq.kepegawaian.tables.records.DaruratPegawaiRecord;
import com.santika.simrs.jooq.kepegawaian.tables.records.DepartemenPegawaiRecord;
import com.santika.simrs.jooq.kepegawaian.tables.records.DokterRecord;
import com.santika.simrs.jooq.kepegawaian.tables.records.DokumenPegawaiRecord;
import com.santika.simrs.jooq.kepegawaian.tables.records.KelompokPegawaiRecord;
import com.santika.simrs.jooq.kepegawaian.tables.records.PegawaiRecord;
import com.santika.simrs.jooq.kepegawaian.tables.records.ResikoPegawaiRecord;
import com.santika.simrs.jooq.kepegawaian.tables.records.SpesialisRecord;
import com.santika.simrs.jooq.kepegawaian.tables.records.VendorTenagaLuarRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * KEPEGAWAIAN.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BidangPegawaiRecord> PK_BIDANG_PEGAWAI = Internal.createUniqueKey(BidangPegawai.BIDANG_PEGAWAI, DSL.name("PK_BIDANG_PEGAWAI"), new TableField[] { BidangPegawai.BIDANG_PEGAWAI.ID }, true);
    public static final UniqueKey<DaruratPegawaiRecord> PK_DARURAT_PEGAWAI = Internal.createUniqueKey(DaruratPegawai.DARURAT_PEGAWAI, DSL.name("PK_DARURAT_PEGAWAI"), new TableField[] { DaruratPegawai.DARURAT_PEGAWAI.ID }, true);
    public static final UniqueKey<DepartemenPegawaiRecord> PK_DEPARTEMEN_PEGAWAI = Internal.createUniqueKey(DepartemenPegawai.DEPARTEMEN_PEGAWAI, DSL.name("PK_DEPARTEMEN_PEGAWAI"), new TableField[] { DepartemenPegawai.DEPARTEMEN_PEGAWAI.ID }, true);
    public static final UniqueKey<DokterRecord> PK_DOKTER = Internal.createUniqueKey(Dokter.DOKTER, DSL.name("PK_DOKTER"), new TableField[] { Dokter.DOKTER.ID }, true);
    public static final UniqueKey<DokumenPegawaiRecord> PK_DOKUMEN_PEGAWAI = Internal.createUniqueKey(DokumenPegawai.DOKUMEN_PEGAWAI, DSL.name("PK_DOKUMEN_PEGAWAI"), new TableField[] { DokumenPegawai.DOKUMEN_PEGAWAI.ID }, true);
    public static final UniqueKey<KelompokPegawaiRecord> PK_KELOMPOK_PEGAWAI = Internal.createUniqueKey(KelompokPegawai.KELOMPOK_PEGAWAI, DSL.name("PK_KELOMPOK_PEGAWAI"), new TableField[] { KelompokPegawai.KELOMPOK_PEGAWAI.ID }, true);
    public static final UniqueKey<PegawaiRecord> PK_PEGAWAI = Internal.createUniqueKey(Pegawai.PEGAWAI, DSL.name("PK_PEGAWAI"), new TableField[] { Pegawai.PEGAWAI.ID }, true);
    public static final UniqueKey<ResikoPegawaiRecord> PK_RESIKO_PEGAWAI = Internal.createUniqueKey(ResikoPegawai.RESIKO_PEGAWAI, DSL.name("PK_RESIKO_PEGAWAI"), new TableField[] { ResikoPegawai.RESIKO_PEGAWAI.ID }, true);
    public static final UniqueKey<SpesialisRecord> PK_SPESIALIS = Internal.createUniqueKey(Spesialis.SPESIALIS, DSL.name("PK_SPESIALIS"), new TableField[] { Spesialis.SPESIALIS.ID }, true);
    public static final UniqueKey<VendorTenagaLuarRecord> PK_VENDOR_TENAGA_LUAR = Internal.createUniqueKey(VendorTenagaLuar.VENDOR_TENAGA_LUAR, DSL.name("PK_VENDOR_TENAGA_LUAR"), new TableField[] { VendorTenagaLuar.VENDOR_TENAGA_LUAR.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DokterRecord, PegawaiRecord> FK_DOKTER_PEGAWAI = Internal.createForeignKey(Dokter.DOKTER, DSL.name("FK_DOKTER_PEGAWAI"), new TableField[] { Dokter.DOKTER.PEGAWAI_ID }, Keys.PK_PEGAWAI, new TableField[] { Pegawai.PEGAWAI.ID }, true);
    public static final ForeignKey<DokterRecord, SpesialisRecord> FK_DOKTER_SPESIALIS = Internal.createForeignKey(Dokter.DOKTER, DSL.name("FK_DOKTER_SPESIALIS"), new TableField[] { Dokter.DOKTER.SPESIALIS_ID }, Keys.PK_SPESIALIS, new TableField[] { Spesialis.SPESIALIS.ID }, true);
    public static final ForeignKey<DokumenPegawaiRecord, PegawaiRecord> FK_DOKUMEN_PEGAWAI_PEGAWAI = Internal.createForeignKey(DokumenPegawai.DOKUMEN_PEGAWAI, DSL.name("FK_DOKUMEN_PEGAWAI_PEGAWAI"), new TableField[] { DokumenPegawai.DOKUMEN_PEGAWAI.PEGAWAI_ID }, Keys.PK_PEGAWAI, new TableField[] { Pegawai.PEGAWAI.ID }, true);
}
