/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian;


import com.santika.simrs.jooq.kepegawaian.tables.BidangPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.DaruratPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.DepartemenPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.Dokter;
import com.santika.simrs.jooq.kepegawaian.tables.DokumenPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.KelompokPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.Pegawai;
import com.santika.simrs.jooq.kepegawaian.tables.ResikoPegawai;
import com.santika.simrs.jooq.kepegawaian.tables.Spesialis;
import com.santika.simrs.jooq.kepegawaian.tables.VendorTenagaLuar;


/**
 * Convenience access to all tables in KEPEGAWAIAN.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>KEPEGAWAIAN.BIDANG_PEGAWAI</code>.
     */
    public static final BidangPegawai BIDANG_PEGAWAI = BidangPegawai.BIDANG_PEGAWAI;

    /**
     * The table <code>KEPEGAWAIAN.DARURAT_PEGAWAI</code>.
     */
    public static final DaruratPegawai DARURAT_PEGAWAI = DaruratPegawai.DARURAT_PEGAWAI;

    /**
     * The table <code>KEPEGAWAIAN.DEPARTEMEN_PEGAWAI</code>.
     */
    public static final DepartemenPegawai DEPARTEMEN_PEGAWAI = DepartemenPegawai.DEPARTEMEN_PEGAWAI;

    /**
     * The table <code>KEPEGAWAIAN.DOKTER</code>.
     */
    public static final Dokter DOKTER = Dokter.DOKTER;

    /**
     * The table <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI</code>.
     */
    public static final DokumenPegawai DOKUMEN_PEGAWAI = DokumenPegawai.DOKUMEN_PEGAWAI;

    /**
     * The table <code>KEPEGAWAIAN.KELOMPOK_PEGAWAI</code>.
     */
    public static final KelompokPegawai KELOMPOK_PEGAWAI = KelompokPegawai.KELOMPOK_PEGAWAI;

    /**
     * The table <code>KEPEGAWAIAN.PEGAWAI</code>.
     */
    public static final Pegawai PEGAWAI = Pegawai.PEGAWAI;

    /**
     * The table <code>KEPEGAWAIAN.RESIKO_PEGAWAI</code>.
     */
    public static final ResikoPegawai RESIKO_PEGAWAI = ResikoPegawai.RESIKO_PEGAWAI;

    /**
     * The table <code>KEPEGAWAIAN.SPESIALIS</code>.
     */
    public static final Spesialis SPESIALIS = Spesialis.SPESIALIS;

    /**
     * The table <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR</code>.
     */
    public static final VendorTenagaLuar VENDOR_TENAGA_LUAR = VendorTenagaLuar.VENDOR_TENAGA_LUAR;
}
