/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables.records;


import com.santika.simrs.jooq.master.tables.MedisDiagnosaIcd10;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedisDiagnosaIcd10Record extends UpdatableRecordImpl<MedisDiagnosaIcd10Record> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>MASTER.MEDIS_DIAGNOSA_ICD10.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_DIAGNOSA_ICD10.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>MASTER.MEDIS_DIAGNOSA_ICD10.KODE_DIAGNOSA</code>.
     */
    public void setKodeDiagnosa(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_DIAGNOSA_ICD10.KODE_DIAGNOSA</code>.
     */
    public String getKodeDiagnosa() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MASTER.MEDIS_DIAGNOSA_ICD10.NAMA_DIAGNOSA</code>.
     */
    public void setNamaDiagnosa(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_DIAGNOSA_ICD10.NAMA_DIAGNOSA</code>.
     */
    public String getNamaDiagnosa() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MASTER.MEDIS_DIAGNOSA_ICD10.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_DIAGNOSA_ICD10.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>MASTER.MEDIS_DIAGNOSA_ICD10.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_DIAGNOSA_ICD10.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>MASTER.MEDIS_DIAGNOSA_ICD10.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_DIAGNOSA_ICD10.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedisDiagnosaIcd10Record
     */
    public MedisDiagnosaIcd10Record() {
        super(MedisDiagnosaIcd10.MEDIS_DIAGNOSA_ICD10);
    }

    /**
     * Create a detached, initialised MedisDiagnosaIcd10Record
     */
    public MedisDiagnosaIcd10Record(UUID id, String kodeDiagnosa, String namaDiagnosa, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(MedisDiagnosaIcd10.MEDIS_DIAGNOSA_ICD10);

        setId(id);
        setKodeDiagnosa(kodeDiagnosa);
        setNamaDiagnosa(namaDiagnosa);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
