/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables.records;


import com.santika.simrs.jooq.master.tables.MedisPoli;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedisPoliRecord extends UpdatableRecordImpl<MedisPoliRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>MASTER.MEDIS_POLI.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_POLI.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>MASTER.MEDIS_POLI.KODE_POLI</code>.
     */
    public void setKodePoli(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_POLI.KODE_POLI</code>.
     */
    public String getKodePoli() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MASTER.MEDIS_POLI.NAMA_POLI</code>.
     */
    public void setNamaPoli(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_POLI.NAMA_POLI</code>.
     */
    public String getNamaPoli() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MASTER.MEDIS_POLI.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_POLI.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>MASTER.MEDIS_POLI.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_POLI.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>MASTER.MEDIS_POLI.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_POLI.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedisPoliRecord
     */
    public MedisPoliRecord() {
        super(MedisPoli.MEDIS_POLI);
    }

    /**
     * Create a detached, initialised MedisPoliRecord
     */
    public MedisPoliRecord(UUID id, String kodePoli, String namaPoli, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(MedisPoli.MEDIS_POLI);

        setId(id);
        setKodePoli(kodePoli);
        setNamaPoli(namaPoli);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
