/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables.records;


import com.santika.simrs.jooq.master.tables.MedisProsedurIcd9;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedisProsedurIcd9Record extends UpdatableRecordImpl<MedisProsedurIcd9Record> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>MASTER.MEDIS_PROSEDUR_ICD9.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_PROSEDUR_ICD9.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>MASTER.MEDIS_PROSEDUR_ICD9.KODE_PROSEDUR</code>.
     */
    public void setKodeProsedur(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_PROSEDUR_ICD9.KODE_PROSEDUR</code>.
     */
    public String getKodeProsedur() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MASTER.MEDIS_PROSEDUR_ICD9.NAMA_PROSEDUR</code>.
     */
    public void setNamaProsedur(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_PROSEDUR_ICD9.NAMA_PROSEDUR</code>.
     */
    public String getNamaProsedur() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MASTER.MEDIS_PROSEDUR_ICD9.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_PROSEDUR_ICD9.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>MASTER.MEDIS_PROSEDUR_ICD9.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_PROSEDUR_ICD9.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>MASTER.MEDIS_PROSEDUR_ICD9.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>MASTER.MEDIS_PROSEDUR_ICD9.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedisProsedurIcd9Record
     */
    public MedisProsedurIcd9Record() {
        super(MedisProsedurIcd9.MEDIS_PROSEDUR_ICD9);
    }

    /**
     * Create a detached, initialised MedisProsedurIcd9Record
     */
    public MedisProsedurIcd9Record(UUID id, String kodeProsedur, String namaProsedur, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(MedisProsedurIcd9.MEDIS_PROSEDUR_ICD9);

        setId(id);
        setKodeProsedur(kodeProsedur);
        setNamaProsedur(namaProsedur);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
