/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables.records;


import com.santika.simrs.jooq.master.tables.SupportPenjamin;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SupportPenjaminRecord extends UpdatableRecordImpl<SupportPenjaminRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>MASTER.SUPPORT_PENJAMIN.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>MASTER.SUPPORT_PENJAMIN.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>MASTER.SUPPORT_PENJAMIN.PENJAMIN</code>.
     */
    public void setPenjamin(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MASTER.SUPPORT_PENJAMIN.PENJAMIN</code>.
     */
    public String getPenjamin() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MASTER.SUPPORT_PENJAMIN.NAMA_PERUSAHAAN_PENJAMIN</code>.
     */
    public void setNamaPerusahaanPenjamin(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MASTER.SUPPORT_PENJAMIN.NAMA_PERUSAHAAN_PENJAMIN</code>.
     */
    public String getNamaPerusahaanPenjamin() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MASTER.SUPPORT_PENJAMIN.ALAMAT_PENJAMIN</code>.
     */
    public void setAlamatPenjamin(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>MASTER.SUPPORT_PENJAMIN.ALAMAT_PENJAMIN</code>.
     */
    public String getAlamatPenjamin() {
        return (String) get(3);
    }

    /**
     * Setter for <code>MASTER.SUPPORT_PENJAMIN.TELEPON_PENJAMIN</code>.
     */
    public void setTeleponPenjamin(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>MASTER.SUPPORT_PENJAMIN.TELEPON_PENJAMIN</code>.
     */
    public String getTeleponPenjamin() {
        return (String) get(4);
    }

    /**
     * Setter for <code>MASTER.SUPPORT_PENJAMIN.PENERIMA_TAGIHAN</code>.
     */
    public void setPenerimaTagihan(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>MASTER.SUPPORT_PENJAMIN.PENERIMA_TAGIHAN</code>.
     */
    public String getPenerimaTagihan() {
        return (String) get(5);
    }

    /**
     * Setter for <code>MASTER.SUPPORT_PENJAMIN.IS_ACTIVE</code>.
     */
    public void setIsActive(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>MASTER.SUPPORT_PENJAMIN.IS_ACTIVE</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>MASTER.SUPPORT_PENJAMIN.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>MASTER.SUPPORT_PENJAMIN.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>MASTER.SUPPORT_PENJAMIN.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>MASTER.SUPPORT_PENJAMIN.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>MASTER.SUPPORT_PENJAMIN.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>MASTER.SUPPORT_PENJAMIN.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SupportPenjaminRecord
     */
    public SupportPenjaminRecord() {
        super(SupportPenjamin.SUPPORT_PENJAMIN);
    }

    /**
     * Create a detached, initialised SupportPenjaminRecord
     */
    public SupportPenjaminRecord(UUID id, String penjamin, String namaPerusahaanPenjamin, String alamatPenjamin, String teleponPenjamin, String penerimaTagihan, Boolean isActive, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(SupportPenjamin.SUPPORT_PENJAMIN);

        setId(id);
        setPenjamin(penjamin);
        setNamaPerusahaanPenjamin(namaPerusahaanPenjamin);
        setAlamatPenjamin(alamatPenjamin);
        setTeleponPenjamin(teleponPenjamin);
        setPenerimaTagihan(penerimaTagihan);
        setIsActive(isActive);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
