/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables.records;


import com.santika.simrs.jooq.master.tables.WilayahProvinsi;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WilayahProvinsiRecord extends UpdatableRecordImpl<WilayahProvinsiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>MASTER.WILAYAH_PROVINSI.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_PROVINSI.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_PROVINSI.KODE_PROVINSI</code>.
     */
    public void setKodeProvinsi(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_PROVINSI.KODE_PROVINSI</code>.
     */
    public String getKodeProvinsi() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_PROVINSI.NAMA_PROVINSI</code>.
     */
    public void setNamaProvinsi(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_PROVINSI.NAMA_PROVINSI</code>.
     */
    public String getNamaProvinsi() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_PROVINSI.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_PROVINSI.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_PROVINSI.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_PROVINSI.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_PROVINSI.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_PROVINSI.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WilayahProvinsiRecord
     */
    public WilayahProvinsiRecord() {
        super(WilayahProvinsi.WILAYAH_PROVINSI);
    }

    /**
     * Create a detached, initialised WilayahProvinsiRecord
     */
    public WilayahProvinsiRecord(UUID id, String kodeProvinsi, String namaProvinsi, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(WilayahProvinsi.WILAYAH_PROVINSI);

        setId(id);
        setKodeProvinsi(kodeProvinsi);
        setNamaProvinsi(namaProvinsi);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
