/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables.records;


import com.santika.simrs.jooq.master.tables.WilayahKecamatan;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WilayahKecamatanRecord extends UpdatableRecordImpl<WilayahKecamatanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>MASTER.WILAYAH_KECAMATAN.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KECAMATAN.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KECAMATAN.KAB_KOTA_ID</code>.
     */
    public void setKabKotaId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KECAMATAN.KAB_KOTA_ID</code>.
     */
    public UUID getKabKotaId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KECAMATAN.KODE_KECAMATAN</code>.
     */
    public void setKodeKecamatan(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KECAMATAN.KODE_KECAMATAN</code>.
     */
    public String getKodeKecamatan() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KECAMATAN.NAMA_KECAMATAN</code>.
     */
    public void setNamaKecamatan(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KECAMATAN.NAMA_KECAMATAN</code>.
     */
    public String getNamaKecamatan() {
        return (String) get(3);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KECAMATAN.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KECAMATAN.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KECAMATAN.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KECAMATAN.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KECAMATAN.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KECAMATAN.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WilayahKecamatanRecord
     */
    public WilayahKecamatanRecord() {
        super(WilayahKecamatan.WILAYAH_KECAMATAN);
    }

    /**
     * Create a detached, initialised WilayahKecamatanRecord
     */
    public WilayahKecamatanRecord(UUID id, UUID kabKotaId, String kodeKecamatan, String namaKecamatan, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(WilayahKecamatan.WILAYAH_KECAMATAN);

        setId(id);
        setKabKotaId(kabKotaId);
        setKodeKecamatan(kodeKecamatan);
        setNamaKecamatan(namaKecamatan);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
