/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables.records;


import com.santika.simrs.jooq.master.tables.WilayahKelurahan;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WilayahKelurahanRecord extends UpdatableRecordImpl<WilayahKelurahanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>MASTER.WILAYAH_KELURAHAN.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KELURAHAN.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KELURAHAN.KECAMATAN_ID</code>.
     */
    public void setKecamatanId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KELURAHAN.KECAMATAN_ID</code>.
     */
    public UUID getKecamatanId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KELURAHAN.KODE_KELURAHAN</code>.
     */
    public void setKodeKelurahan(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KELURAHAN.KODE_KELURAHAN</code>.
     */
    public String getKodeKelurahan() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KELURAHAN.NAMA_KELURAHAN</code>.
     */
    public void setNamaKelurahan(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KELURAHAN.NAMA_KELURAHAN</code>.
     */
    public String getNamaKelurahan() {
        return (String) get(3);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KELURAHAN.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KELURAHAN.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KELURAHAN.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KELURAHAN.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KELURAHAN.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KELURAHAN.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WilayahKelurahanRecord
     */
    public WilayahKelurahanRecord() {
        super(WilayahKelurahan.WILAYAH_KELURAHAN);
    }

    /**
     * Create a detached, initialised WilayahKelurahanRecord
     */
    public WilayahKelurahanRecord(UUID id, UUID kecamatanId, String kodeKelurahan, String namaKelurahan, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(WilayahKelurahan.WILAYAH_KELURAHAN);

        setId(id);
        setKecamatanId(kecamatanId);
        setKodeKelurahan(kodeKelurahan);
        setNamaKelurahan(namaKelurahan);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
