/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables.records;


import com.santika.simrs.jooq.master.tables.WilayahKabKota;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WilayahKabKotaRecord extends UpdatableRecordImpl<WilayahKabKotaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>MASTER.WILAYAH_KAB_KOTA.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KAB_KOTA.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KAB_KOTA.PROVINSI_ID</code>.
     */
    public void setProvinsiId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KAB_KOTA.PROVINSI_ID</code>.
     */
    public UUID getProvinsiId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KAB_KOTA.KODE_KAB_KOTA</code>.
     */
    public void setKodeKabKota(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KAB_KOTA.KODE_KAB_KOTA</code>.
     */
    public String getKodeKabKota() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KAB_KOTA.NAMA_KAB_KOTA</code>.
     */
    public void setNamaKabKota(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KAB_KOTA.NAMA_KAB_KOTA</code>.
     */
    public String getNamaKabKota() {
        return (String) get(3);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KAB_KOTA.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KAB_KOTA.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KAB_KOTA.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KAB_KOTA.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>MASTER.WILAYAH_KAB_KOTA.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>MASTER.WILAYAH_KAB_KOTA.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WilayahKabKotaRecord
     */
    public WilayahKabKotaRecord() {
        super(WilayahKabKota.WILAYAH_KAB_KOTA);
    }

    /**
     * Create a detached, initialised WilayahKabKotaRecord
     */
    public WilayahKabKotaRecord(UUID id, UUID provinsiId, String kodeKabKota, String namaKabKota, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(WilayahKabKota.WILAYAH_KAB_KOTA);

        setId(id);
        setProvinsiId(provinsiId);
        setKodeKabKota(kodeKabKota);
        setNamaKabKota(namaKabKota);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
