/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared;


import com.santika.simrs.jooq.shared.tables.StorageFiles;
import com.santika.simrs.jooq.shared.tables.TempFiles;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in SHARED.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_STORAGE_FILES_DELETED_AT = Internal.createIndex(DSL.name("IDX_STORAGE_FILES_DELETED_AT"), StorageFiles.STORAGE_FILES, new OrderField[] { StorageFiles.STORAGE_FILES.DELETED_AT }, false);
    public static final Index IDX_STORAGE_FILES_MODULE_ENTITY = Internal.createIndex(DSL.name("IDX_STORAGE_FILES_MODULE_ENTITY"), StorageFiles.STORAGE_FILES, new OrderField[] { StorageFiles.STORAGE_FILES.MODULE, StorageFiles.STORAGE_FILES.ENTITY_ID }, false);
    public static final Index IDX_STORAGE_FILES_UPLOADED_BY = Internal.createIndex(DSL.name("IDX_STORAGE_FILES_UPLOADED_BY"), StorageFiles.STORAGE_FILES, new OrderField[] { StorageFiles.STORAGE_FILES.UPLOADED_BY }, false);
    public static final Index IDX_TEMP_FILES_EXPIRES_AT = Internal.createIndex(DSL.name("IDX_TEMP_FILES_EXPIRES_AT"), TempFiles.TEMP_FILES, new OrderField[] { TempFiles.TEMP_FILES.EXPIRES_AT }, false);
    public static final Index IDX_TEMP_FILES_UPLOAD_TOKEN = Internal.createIndex(DSL.name("IDX_TEMP_FILES_UPLOAD_TOKEN"), TempFiles.TEMP_FILES, new OrderField[] { TempFiles.TEMP_FILES.UPLOAD_TOKEN }, false);
    public static final Index IDX_TEMP_FILES_UPLOADED_BY = Internal.createIndex(DSL.name("IDX_TEMP_FILES_UPLOADED_BY"), TempFiles.TEMP_FILES, new OrderField[] { TempFiles.TEMP_FILES.UPLOADED_BY }, false);
}
