/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared;


import com.santika.simrs.jooq.shared.tables.Audit;
import com.santika.simrs.jooq.shared.tables.File;
import com.santika.simrs.jooq.shared.tables.Permissions;
import com.santika.simrs.jooq.shared.tables.RoleHasPermission;
import com.santika.simrs.jooq.shared.tables.Roles;
import com.santika.simrs.jooq.shared.tables.StorageFiles;
import com.santika.simrs.jooq.shared.tables.TempFiles;
import com.santika.simrs.jooq.shared.tables.UserHasRole;
import com.santika.simrs.jooq.shared.tables.UserSessions;
import com.santika.simrs.jooq.shared.tables.Users;
import com.santika.simrs.jooq.shared.tables.records.AuditRecord;
import com.santika.simrs.jooq.shared.tables.records.FileRecord;
import com.santika.simrs.jooq.shared.tables.records.PermissionsRecord;
import com.santika.simrs.jooq.shared.tables.records.RoleHasPermissionRecord;
import com.santika.simrs.jooq.shared.tables.records.RolesRecord;
import com.santika.simrs.jooq.shared.tables.records.StorageFilesRecord;
import com.santika.simrs.jooq.shared.tables.records.TempFilesRecord;
import com.santika.simrs.jooq.shared.tables.records.UserHasRoleRecord;
import com.santika.simrs.jooq.shared.tables.records.UserSessionsRecord;
import com.santika.simrs.jooq.shared.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * SHARED.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuditRecord> PK_AUDIT = Internal.createUniqueKey(Audit.AUDIT, DSL.name("PK_AUDIT"), new TableField[] { Audit.AUDIT.ID }, true);
    public static final UniqueKey<FileRecord> PK_FILE = Internal.createUniqueKey(File.FILE, DSL.name("PK_FILE"), new TableField[] { File.FILE.ID }, true);
    public static final UniqueKey<PermissionsRecord> PK_PERMISSIONS = Internal.createUniqueKey(Permissions.PERMISSIONS, DSL.name("PK_PERMISSIONS"), new TableField[] { Permissions.PERMISSIONS.ID }, true);
    public static final UniqueKey<RoleHasPermissionRecord> PK_ROLE_HAS_PERMISSION = Internal.createUniqueKey(RoleHasPermission.ROLE_HAS_PERMISSION, DSL.name("PK_ROLE_HAS_PERMISSION"), new TableField[] { RoleHasPermission.ROLE_HAS_PERMISSION.ROLE_ID, RoleHasPermission.ROLE_HAS_PERMISSION.PERMISSION_ID }, true);
    public static final UniqueKey<RolesRecord> PK_ROLES = Internal.createUniqueKey(Roles.ROLES, DSL.name("PK_ROLES"), new TableField[] { Roles.ROLES.ID }, true);
    public static final UniqueKey<StorageFilesRecord> PK_STORAGE_FILES = Internal.createUniqueKey(StorageFiles.STORAGE_FILES, DSL.name("PK_STORAGE_FILES"), new TableField[] { StorageFiles.STORAGE_FILES.ID }, true);
    public static final UniqueKey<TempFilesRecord> CONSTRAINT_8 = Internal.createUniqueKey(TempFiles.TEMP_FILES, DSL.name("CONSTRAINT_8"), new TableField[] { TempFiles.TEMP_FILES.UPLOAD_TOKEN }, true);
    public static final UniqueKey<TempFilesRecord> PK_TEMP_FILES = Internal.createUniqueKey(TempFiles.TEMP_FILES, DSL.name("PK_TEMP_FILES"), new TableField[] { TempFiles.TEMP_FILES.ID }, true);
    public static final UniqueKey<UserHasRoleRecord> PK_USER_HAS_ROLE = Internal.createUniqueKey(UserHasRole.USER_HAS_ROLE, DSL.name("PK_USER_HAS_ROLE"), new TableField[] { UserHasRole.USER_HAS_ROLE.USER_ID, UserHasRole.USER_HAS_ROLE.ROLE_ID }, true);
    public static final UniqueKey<UserSessionsRecord> PK_USER_SESSIONS = Internal.createUniqueKey(UserSessions.USER_SESSIONS, DSL.name("PK_USER_SESSIONS"), new TableField[] { UserSessions.USER_SESSIONS.ID }, true);
    public static final UniqueKey<UsersRecord> PK_USERS = Internal.createUniqueKey(Users.USERS, DSL.name("PK_USERS"), new TableField[] { Users.USERS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<RoleHasPermissionRecord, PermissionsRecord> FK_RHP_PERMISSION_ID = Internal.createForeignKey(RoleHasPermission.ROLE_HAS_PERMISSION, DSL.name("FK_RHP_PERMISSION_ID"), new TableField[] { RoleHasPermission.ROLE_HAS_PERMISSION.PERMISSION_ID }, Keys.PK_PERMISSIONS, new TableField[] { Permissions.PERMISSIONS.ID }, true);
    public static final ForeignKey<RoleHasPermissionRecord, RolesRecord> FK_RHP_ROLE_ID = Internal.createForeignKey(RoleHasPermission.ROLE_HAS_PERMISSION, DSL.name("FK_RHP_ROLE_ID"), new TableField[] { RoleHasPermission.ROLE_HAS_PERMISSION.ROLE_ID }, Keys.PK_ROLES, new TableField[] { Roles.ROLES.ID }, true);
    public static final ForeignKey<StorageFilesRecord, UsersRecord> FK_STORAGE_FILES_UPLOADED_BY = Internal.createForeignKey(StorageFiles.STORAGE_FILES, DSL.name("FK_STORAGE_FILES_UPLOADED_BY"), new TableField[] { StorageFiles.STORAGE_FILES.UPLOADED_BY }, Keys.PK_USERS, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<TempFilesRecord, UsersRecord> FK_TEMP_FILES_UPLOADED_BY = Internal.createForeignKey(TempFiles.TEMP_FILES, DSL.name("FK_TEMP_FILES_UPLOADED_BY"), new TableField[] { TempFiles.TEMP_FILES.UPLOADED_BY }, Keys.PK_USERS, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<UserHasRoleRecord, RolesRecord> FK_UHR_ROLE_ID = Internal.createForeignKey(UserHasRole.USER_HAS_ROLE, DSL.name("FK_UHR_ROLE_ID"), new TableField[] { UserHasRole.USER_HAS_ROLE.ROLE_ID }, Keys.PK_ROLES, new TableField[] { Roles.ROLES.ID }, true);
    public static final ForeignKey<UserHasRoleRecord, UsersRecord> FK_UHR_USER_ID = Internal.createForeignKey(UserHasRole.USER_HAS_ROLE, DSL.name("FK_UHR_USER_ID"), new TableField[] { UserHasRole.USER_HAS_ROLE.USER_ID }, Keys.PK_USERS, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<UserSessionsRecord, UsersRecord> FK_USER_SESSIONS_USER_ID = Internal.createForeignKey(UserSessions.USER_SESSIONS, DSL.name("FK_USER_SESSIONS_USER_ID"), new TableField[] { UserSessions.USER_SESSIONS.USER_ID }, Keys.PK_USERS, new TableField[] { Users.USERS.ID }, true);
}
