/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared;


import com.santika.simrs.jooq.DefaultCatalog;
import com.santika.simrs.jooq.shared.tables.Audit;
import com.santika.simrs.jooq.shared.tables.File;
import com.santika.simrs.jooq.shared.tables.Permissions;
import com.santika.simrs.jooq.shared.tables.RoleHasPermission;
import com.santika.simrs.jooq.shared.tables.Roles;
import com.santika.simrs.jooq.shared.tables.StorageFiles;
import com.santika.simrs.jooq.shared.tables.TempFiles;
import com.santika.simrs.jooq.shared.tables.UserHasRole;
import com.santika.simrs.jooq.shared.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Shared extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SHARED</code>
     */
    public static final Shared SHARED = new Shared();

    /**
     * The table <code>SHARED.AUDIT</code>.
     */
    public final Audit AUDIT = Audit.AUDIT;

    /**
     * The table <code>SHARED.FILE</code>.
     */
    public final File FILE = File.FILE;

    /**
     * The table <code>SHARED.PERMISSIONS</code>.
     */
    public final Permissions PERMISSIONS = Permissions.PERMISSIONS;

    /**
     * The table <code>SHARED.ROLE_HAS_PERMISSION</code>.
     */
    public final RoleHasPermission ROLE_HAS_PERMISSION = RoleHasPermission.ROLE_HAS_PERMISSION;

    /**
     * The table <code>SHARED.ROLES</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>SHARED.STORAGE_FILES</code>.
     */
    public final StorageFiles STORAGE_FILES = StorageFiles.STORAGE_FILES;

    /**
     * The table <code>SHARED.TEMP_FILES</code>.
     */
    public final TempFiles TEMP_FILES = TempFiles.TEMP_FILES;

    /**
     * The table <code>SHARED.USER_HAS_ROLE</code>.
     */
    public final UserHasRole USER_HAS_ROLE = UserHasRole.USER_HAS_ROLE;

    /**
     * The table <code>SHARED.USERS</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Shared() {
        super("SHARED", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Audit.AUDIT,
            File.FILE,
            Permissions.PERMISSIONS,
            RoleHasPermission.ROLE_HAS_PERMISSION,
            Roles.ROLES,
            StorageFiles.STORAGE_FILES,
            TempFiles.TEMP_FILES,
            UserHasRole.USER_HAS_ROLE,
            Users.USERS
        );
    }
}
