/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared;


import com.santika.simrs.jooq.shared.tables.Audit;
import com.santika.simrs.jooq.shared.tables.File;
import com.santika.simrs.jooq.shared.tables.Permissions;
import com.santika.simrs.jooq.shared.tables.RoleHasPermission;
import com.santika.simrs.jooq.shared.tables.Roles;
import com.santika.simrs.jooq.shared.tables.StorageFiles;
import com.santika.simrs.jooq.shared.tables.TempFiles;
import com.santika.simrs.jooq.shared.tables.UserHasRole;
import com.santika.simrs.jooq.shared.tables.UserSessions;
import com.santika.simrs.jooq.shared.tables.Users;


/**
 * Convenience access to all tables in SHARED.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>SHARED.AUDIT</code>.
     */
    public static final Audit AUDIT = Audit.AUDIT;

    /**
     * The table <code>SHARED.FILE</code>.
     */
    public static final File FILE = File.FILE;

    /**
     * The table <code>SHARED.PERMISSIONS</code>.
     */
    public static final Permissions PERMISSIONS = Permissions.PERMISSIONS;

    /**
     * The table <code>SHARED.ROLE_HAS_PERMISSION</code>.
     */
    public static final RoleHasPermission ROLE_HAS_PERMISSION = RoleHasPermission.ROLE_HAS_PERMISSION;

    /**
     * The table <code>SHARED.ROLES</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>SHARED.STORAGE_FILES</code>.
     */
    public static final StorageFiles STORAGE_FILES = StorageFiles.STORAGE_FILES;

    /**
     * The table <code>SHARED.TEMP_FILES</code>.
     */
    public static final TempFiles TEMP_FILES = TempFiles.TEMP_FILES;

    /**
     * The table <code>SHARED.USER_HAS_ROLE</code>.
     */
    public static final UserHasRole USER_HAS_ROLE = UserHasRole.USER_HAS_ROLE;

    /**
     * The table <code>SHARED.USER_SESSIONS</code>.
     */
    public static final UserSessions USER_SESSIONS = UserSessions.USER_SESSIONS;

    /**
     * The table <code>SHARED.USERS</code>.
     */
    public static final Users USERS = Users.USERS;
}
