/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables.records;


import com.santika.simrs.jooq.kepegawaian.tables.BidangPegawai;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BidangPegawaiRecord extends UpdatableRecordImpl<BidangPegawaiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>KEPEGAWAIAN.BIDANG_PEGAWAI.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.BIDANG_PEGAWAI.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.BIDANG_PEGAWAI.KODE_BIDANG</code>.
     */
    public void setKodeBidang(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.BIDANG_PEGAWAI.KODE_BIDANG</code>.
     */
    public String getKodeBidang() {
        return (String) get(1);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.BIDANG_PEGAWAI.NAMA_BIDANG</code>.
     */
    public void setNamaBidang(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.BIDANG_PEGAWAI.NAMA_BIDANG</code>.
     */
    public String getNamaBidang() {
        return (String) get(2);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.BIDANG_PEGAWAI.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.BIDANG_PEGAWAI.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.BIDANG_PEGAWAI.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.BIDANG_PEGAWAI.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.BIDANG_PEGAWAI.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.BIDANG_PEGAWAI.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BidangPegawaiRecord
     */
    public BidangPegawaiRecord() {
        super(BidangPegawai.BIDANG_PEGAWAI);
    }

    /**
     * Create a detached, initialised BidangPegawaiRecord
     */
    public BidangPegawaiRecord(UUID id, String kodeBidang, String namaBidang, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(BidangPegawai.BIDANG_PEGAWAI);

        setId(id);
        setKodeBidang(kodeBidang);
        setNamaBidang(namaBidang);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
