/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables.records;


import com.santika.simrs.jooq.kepegawaian.tables.DaruratPegawai;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DaruratPegawaiRecord extends UpdatableRecordImpl<DaruratPegawaiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>KEPEGAWAIAN.DARURAT_PEGAWAI.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DARURAT_PEGAWAI.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DARURAT_PEGAWAI.KODE_EMERGENCY</code>.
     */
    public void setKodeEmergency(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DARURAT_PEGAWAI.KODE_EMERGENCY</code>.
     */
    public String getKodeEmergency() {
        return (String) get(1);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DARURAT_PEGAWAI.NAMA_EMERGENCY</code>.
     */
    public void setNamaEmergency(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DARURAT_PEGAWAI.NAMA_EMERGENCY</code>.
     */
    public String getNamaEmergency() {
        return (String) get(2);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DARURAT_PEGAWAI.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DARURAT_PEGAWAI.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DARURAT_PEGAWAI.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DARURAT_PEGAWAI.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DARURAT_PEGAWAI.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DARURAT_PEGAWAI.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DaruratPegawaiRecord
     */
    public DaruratPegawaiRecord() {
        super(DaruratPegawai.DARURAT_PEGAWAI);
    }

    /**
     * Create a detached, initialised DaruratPegawaiRecord
     */
    public DaruratPegawaiRecord(UUID id, String kodeEmergency, String namaEmergency, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(DaruratPegawai.DARURAT_PEGAWAI);

        setId(id);
        setKodeEmergency(kodeEmergency);
        setNamaEmergency(namaEmergency);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
