/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables.records;


import com.santika.simrs.jooq.kepegawaian.tables.Dokter;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DokterRecord extends UpdatableRecordImpl<DokterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>KEPEGAWAIAN.DOKTER.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKTER.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKTER.PEGAWAI_ID</code>.
     */
    public void setPegawaiId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKTER.PEGAWAI_ID</code>.
     */
    public UUID getPegawaiId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKTER.NAMA_DOKTER</code>.
     */
    public void setNamaDokter(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKTER.NAMA_DOKTER</code>.
     */
    public String getNamaDokter() {
        return (String) get(2);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKTER.NIP</code>.
     */
    public void setNip(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKTER.NIP</code>.
     */
    public String getNip() {
        return (String) get(3);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKTER.TELEPHONE_DOKTER</code>.
     */
    public void setTelephoneDokter(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKTER.TELEPHONE_DOKTER</code>.
     */
    public String getTelephoneDokter() {
        return (String) get(4);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKTER.EMAIL_DOKTER</code>.
     */
    public void setEmailDokter(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKTER.EMAIL_DOKTER</code>.
     */
    public String getEmailDokter() {
        return (String) get(5);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKTER.SPESIALIS_ID</code>.
     */
    public void setSpesialisId(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKTER.SPESIALIS_ID</code>.
     */
    public UUID getSpesialisId() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKTER.ALUMNI</code>.
     */
    public void setAlumni(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKTER.ALUMNI</code>.
     */
    public String getAlumni() {
        return (String) get(7);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKTER.NO_IJIN_PRAKTEK</code>.
     */
    public void setNoIjinPraktek(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKTER.NO_IJIN_PRAKTEK</code>.
     */
    public String getNoIjinPraktek() {
        return (String) get(8);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKTER.IS_ACTIVE</code>.
     */
    public void setIsActive(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKTER.IS_ACTIVE</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKTER.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKTER.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKTER.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKTER.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKTER.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKTER.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DokterRecord
     */
    public DokterRecord() {
        super(Dokter.DOKTER);
    }

    /**
     * Create a detached, initialised DokterRecord
     */
    public DokterRecord(UUID id, UUID pegawaiId, String namaDokter, String nip, String telephoneDokter, String emailDokter, UUID spesialisId, String alumni, String noIjinPraktek, Boolean isActive, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Dokter.DOKTER);

        setId(id);
        setPegawaiId(pegawaiId);
        setNamaDokter(namaDokter);
        setNip(nip);
        setTelephoneDokter(telephoneDokter);
        setEmailDokter(emailDokter);
        setSpesialisId(spesialisId);
        setAlumni(alumni);
        setNoIjinPraktek(noIjinPraktek);
        setIsActive(isActive);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
