/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables.records;


import com.santika.simrs.jooq.kepegawaian.tables.DokumenPegawai;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DokumenPegawaiRecord extends UpdatableRecordImpl<DokumenPegawaiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.PEGAWAI_ID</code>.
     */
    public void setPegawaiId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.PEGAWAI_ID</code>.
     */
    public UUID getPegawaiId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.NAMA_DOKUMEN</code>.
     */
    public void setNamaDokumen(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.NAMA_DOKUMEN</code>.
     */
    public String getNamaDokumen() {
        return (String) get(2);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.FILE_ID</code>.
     */
    public void setFileId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.FILE_ID</code>.
     */
    public UUID getFileId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.IS_ACTIVE</code>.
     */
    public void setIsActive(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.IS_ACTIVE</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.DOKUMEN_PEGAWAI.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DokumenPegawaiRecord
     */
    public DokumenPegawaiRecord() {
        super(DokumenPegawai.DOKUMEN_PEGAWAI);
    }

    /**
     * Create a detached, initialised DokumenPegawaiRecord
     */
    public DokumenPegawaiRecord(UUID id, UUID pegawaiId, String namaDokumen, UUID fileId, Boolean isActive, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(DokumenPegawai.DOKUMEN_PEGAWAI);

        setId(id);
        setPegawaiId(pegawaiId);
        setNamaDokumen(namaDokumen);
        setFileId(fileId);
        setIsActive(isActive);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
