/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables.records;


import com.santika.simrs.jooq.kepegawaian.tables.Pegawai;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PegawaiRecord extends UpdatableRecordImpl<PegawaiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.NAMA</code>.
     */
    public void setNama(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.NAMA</code>.
     */
    public String getNama() {
        return (String) get(1);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.NIP</code>.
     */
    public void setNip(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.NIP</code>.
     */
    public String getNip() {
        return (String) get(2);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.JENIS_IDENTITAS</code>.
     */
    public void setJenisIdentitas(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.JENIS_IDENTITAS</code>.
     */
    public String getJenisIdentitas() {
        return (String) get(3);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.IDENTITAS_LAIN</code>.
     */
    public void setIdentitasLain(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.IDENTITAS_LAIN</code>.
     */
    public String getIdentitasLain() {
        return (String) get(4);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.NO_IDENTITAS</code>.
     */
    public void setNoIdentitas(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.NO_IDENTITAS</code>.
     */
    public String getNoIdentitas() {
        return (String) get(5);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.KELAMIN</code>.
     */
    public void setKelamin(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.KELAMIN</code>.
     */
    public String getKelamin() {
        return (String) get(6);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.JABATAN</code>.
     */
    public void setJabatan(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.JABATAN</code>.
     */
    public String getJabatan() {
        return (String) get(7);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.TELEPHONE</code>.
     */
    public void setTelephone(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.TELEPHONE</code>.
     */
    public String getTelephone() {
        return (String) get(8);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(9);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.JENJANG_JABATAN</code>.
     */
    public void setJenjangJabatan(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.JENJANG_JABATAN</code>.
     */
    public String getJenjangJabatan() {
        return (String) get(10);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.KELOMPOK_PEGAWAI_ID</code>.
     */
    public void setKelompokPegawaiId(UUID value) {
        set(11, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.KELOMPOK_PEGAWAI_ID</code>.
     */
    public UUID getKelompokPegawaiId() {
        return (UUID) get(11);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.RESIKO_PEGAWAI_ID</code>.
     */
    public void setResikoPegawaiId(UUID value) {
        set(12, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.RESIKO_PEGAWAI_ID</code>.
     */
    public UUID getResikoPegawaiId() {
        return (UUID) get(12);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.DARURAT_PEGAWAI_ID</code>.
     */
    public void setDaruratPegawaiId(UUID value) {
        set(13, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.DARURAT_PEGAWAI_ID</code>.
     */
    public UUID getDaruratPegawaiId() {
        return (UUID) get(13);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.DEPARTEMEN_PEGAWAI_ID</code>.
     */
    public void setDepartemenPegawaiId(UUID value) {
        set(14, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.DEPARTEMEN_PEGAWAI_ID</code>.
     */
    public UUID getDepartemenPegawaiId() {
        return (UUID) get(14);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.BIDANG_PEGAWAI_ID</code>.
     */
    public void setBidangPegawaiId(UUID value) {
        set(15, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.BIDANG_PEGAWAI_ID</code>.
     */
    public UUID getBidangPegawaiId() {
        return (UUID) get(15);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.STATUS_PEGAWAI</code>.
     */
    public void setStatusPegawai(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.STATUS_PEGAWAI</code>.
     */
    public String getStatusPegawai() {
        return (String) get(16);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.VENDOR_TENAGA_LUAR_ID</code>.
     */
    public void setVendorTenagaLuarId(UUID value) {
        set(17, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.VENDOR_TENAGA_LUAR_ID</code>.
     */
    public UUID getVendorTenagaLuarId() {
        return (UUID) get(17);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.PENDIDIKAN</code>.
     */
    public void setPendidikan(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.PENDIDIKAN</code>.
     */
    public String getPendidikan() {
        return (String) get(18);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.TEMPAT_LAHIR</code>.
     */
    public void setTempatLahir(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.TEMPAT_LAHIR</code>.
     */
    public String getTempatLahir() {
        return (String) get(19);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.TANGGAL_LAHIR</code>.
     */
    public void setTanggalLahir(LocalDate value) {
        set(20, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.TANGGAL_LAHIR</code>.
     */
    public LocalDate getTanggalLahir() {
        return (LocalDate) get(20);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.PROVINSI_ID</code>.
     */
    public void setProvinsiId(UUID value) {
        set(21, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.PROVINSI_ID</code>.
     */
    public UUID getProvinsiId() {
        return (UUID) get(21);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.KABUPATEN_ID</code>.
     */
    public void setKabupatenId(UUID value) {
        set(22, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.KABUPATEN_ID</code>.
     */
    public UUID getKabupatenId() {
        return (UUID) get(22);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.KECAMATAN_ID</code>.
     */
    public void setKecamatanId(UUID value) {
        set(23, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.KECAMATAN_ID</code>.
     */
    public UUID getKecamatanId() {
        return (UUID) get(23);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.KELURAHAN_ID</code>.
     */
    public void setKelurahanId(UUID value) {
        set(24, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.KELURAHAN_ID</code>.
     */
    public UUID getKelurahanId() {
        return (UUID) get(24);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.ALAMAT</code>.
     */
    public void setAlamat(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.ALAMAT</code>.
     */
    public String getAlamat() {
        return (String) get(25);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.MULAI_BEKERJA</code>.
     */
    public void setMulaiBekerja(LocalDate value) {
        set(26, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.MULAI_BEKERJA</code>.
     */
    public LocalDate getMulaiBekerja() {
        return (LocalDate) get(26);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.FOTO_ID</code>.
     */
    public void setFotoId(UUID value) {
        set(27, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.FOTO_ID</code>.
     */
    public UUID getFotoId() {
        return (UUID) get(27);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.IS_ACTIVE</code>.
     */
    public void setIsActive(Boolean value) {
        set(28, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.IS_ACTIVE</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(28);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(29, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(29);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(30, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(30);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.PEGAWAI.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(31, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.PEGAWAI.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(31);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PegawaiRecord
     */
    public PegawaiRecord() {
        super(Pegawai.PEGAWAI);
    }

    /**
     * Create a detached, initialised PegawaiRecord
     */
    public PegawaiRecord(UUID id, String nama, String nip, String jenisIdentitas, String identitasLain, String noIdentitas, String kelamin, String jabatan, String telephone, String email, String jenjangJabatan, UUID kelompokPegawaiId, UUID resikoPegawaiId, UUID daruratPegawaiId, UUID departemenPegawaiId, UUID bidangPegawaiId, String statusPegawai, UUID vendorTenagaLuarId, String pendidikan, String tempatLahir, LocalDate tanggalLahir, UUID provinsiId, UUID kabupatenId, UUID kecamatanId, UUID kelurahanId, String alamat, LocalDate mulaiBekerja, UUID fotoId, Boolean isActive, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Pegawai.PEGAWAI);

        setId(id);
        setNama(nama);
        setNip(nip);
        setJenisIdentitas(jenisIdentitas);
        setIdentitasLain(identitasLain);
        setNoIdentitas(noIdentitas);
        setKelamin(kelamin);
        setJabatan(jabatan);
        setTelephone(telephone);
        setEmail(email);
        setJenjangJabatan(jenjangJabatan);
        setKelompokPegawaiId(kelompokPegawaiId);
        setResikoPegawaiId(resikoPegawaiId);
        setDaruratPegawaiId(daruratPegawaiId);
        setDepartemenPegawaiId(departemenPegawaiId);
        setBidangPegawaiId(bidangPegawaiId);
        setStatusPegawai(statusPegawai);
        setVendorTenagaLuarId(vendorTenagaLuarId);
        setPendidikan(pendidikan);
        setTempatLahir(tempatLahir);
        setTanggalLahir(tanggalLahir);
        setProvinsiId(provinsiId);
        setKabupatenId(kabupatenId);
        setKecamatanId(kecamatanId);
        setKelurahanId(kelurahanId);
        setAlamat(alamat);
        setMulaiBekerja(mulaiBekerja);
        setFotoId(fotoId);
        setIsActive(isActive);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
