/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables.records;


import com.santika.simrs.jooq.kepegawaian.tables.Spesialis;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpesialisRecord extends UpdatableRecordImpl<SpesialisRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>KEPEGAWAIAN.SPESIALIS.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.SPESIALIS.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.SPESIALIS.KODE_SPESIALIS</code>.
     */
    public void setKodeSpesialis(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.SPESIALIS.KODE_SPESIALIS</code>.
     */
    public String getKodeSpesialis() {
        return (String) get(1);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.SPESIALIS.NAMA_SPESIALIS</code>.
     */
    public void setNamaSpesialis(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.SPESIALIS.NAMA_SPESIALIS</code>.
     */
    public String getNamaSpesialis() {
        return (String) get(2);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.SPESIALIS.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.SPESIALIS.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.SPESIALIS.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.SPESIALIS.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.SPESIALIS.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.SPESIALIS.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpesialisRecord
     */
    public SpesialisRecord() {
        super(Spesialis.SPESIALIS);
    }

    /**
     * Create a detached, initialised SpesialisRecord
     */
    public SpesialisRecord(UUID id, String kodeSpesialis, String namaSpesialis, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Spesialis.SPESIALIS);

        setId(id);
        setKodeSpesialis(kodeSpesialis);
        setNamaSpesialis(namaSpesialis);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
