/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.kepegawaian.tables.records;


import com.santika.simrs.jooq.kepegawaian.tables.VendorTenagaLuar;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VendorTenagaLuarRecord extends UpdatableRecordImpl<VendorTenagaLuarRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.NAMA_VENDOR</code>.
     */
    public void setNamaVendor(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.NAMA_VENDOR</code>.
     */
    public String getNamaVendor() {
        return (String) get(1);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.ALAMAT_VENDOR</code>.
     */
    public void setAlamatVendor(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.ALAMAT_VENDOR</code>.
     */
    public String getAlamatVendor() {
        return (String) get(2);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.BIDANG_VENDOR</code>.
     */
    public void setBidangVendor(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.BIDANG_VENDOR</code>.
     */
    public String getBidangVendor() {
        return (String) get(3);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.TELEPHONE_VENDOR</code>.
     */
    public void setTelephoneVendor(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.TELEPHONE_VENDOR</code>.
     */
    public String getTelephoneVendor() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.NAMA_KONTAK_DARURAT</code>.
     */
    public void setNamaKontakDarurat(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.NAMA_KONTAK_DARURAT</code>.
     */
    public String getNamaKontakDarurat() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.KONTAK_DARURAT_VENDOR</code>.
     */
    public void setKontakDaruratVendor(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.KONTAK_DARURAT_VENDOR</code>.
     */
    public String getKontakDaruratVendor() {
        return (String) get(6);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>KEPEGAWAIAN.VENDOR_TENAGA_LUAR.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VendorTenagaLuarRecord
     */
    public VendorTenagaLuarRecord() {
        super(VendorTenagaLuar.VENDOR_TENAGA_LUAR);
    }

    /**
     * Create a detached, initialised VendorTenagaLuarRecord
     */
    public VendorTenagaLuarRecord(UUID id, String namaVendor, String alamatVendor, String bidangVendor, String telephoneVendor, String namaKontakDarurat, String kontakDaruratVendor, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(VendorTenagaLuar.VENDOR_TENAGA_LUAR);

        setId(id);
        setNamaVendor(namaVendor);
        setAlamatVendor(alamatVendor);
        setBidangVendor(bidangVendor);
        setTelephoneVendor(telephoneVendor);
        setNamaKontakDarurat(namaKontakDarurat);
        setKontakDaruratVendor(kontakDaruratVendor);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
