/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master;


import com.santika.simrs.jooq.master.tables.MedisDiagnosaIcd10;
import com.santika.simrs.jooq.master.tables.MedisPoli;
import com.santika.simrs.jooq.master.tables.MedisProsedurIcd9;
import com.santika.simrs.jooq.master.tables.SupportPenjamin;
import com.santika.simrs.jooq.master.tables.WilayahKabKota;
import com.santika.simrs.jooq.master.tables.WilayahKecamatan;
import com.santika.simrs.jooq.master.tables.WilayahKelurahan;
import com.santika.simrs.jooq.master.tables.WilayahProvinsi;
import com.santika.simrs.jooq.master.tables.records.MedisDiagnosaIcd10Record;
import com.santika.simrs.jooq.master.tables.records.MedisPoliRecord;
import com.santika.simrs.jooq.master.tables.records.MedisProsedurIcd9Record;
import com.santika.simrs.jooq.master.tables.records.SupportPenjaminRecord;
import com.santika.simrs.jooq.master.tables.records.WilayahKabKotaRecord;
import com.santika.simrs.jooq.master.tables.records.WilayahKecamatanRecord;
import com.santika.simrs.jooq.master.tables.records.WilayahKelurahanRecord;
import com.santika.simrs.jooq.master.tables.records.WilayahProvinsiRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * MASTER.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MedisDiagnosaIcd10Record> PK_MEDIS_DIAGNOSA_ICD10 = Internal.createUniqueKey(MedisDiagnosaIcd10.MEDIS_DIAGNOSA_ICD10, DSL.name("PK_MEDIS_DIAGNOSA_ICD10"), new TableField[] { MedisDiagnosaIcd10.MEDIS_DIAGNOSA_ICD10.ID }, true);
    public static final UniqueKey<MedisPoliRecord> PK_MEDIS_POLI = Internal.createUniqueKey(MedisPoli.MEDIS_POLI, DSL.name("PK_MEDIS_POLI"), new TableField[] { MedisPoli.MEDIS_POLI.ID }, true);
    public static final UniqueKey<MedisProsedurIcd9Record> PK_MEDIS_PROSEDUR_ICD9 = Internal.createUniqueKey(MedisProsedurIcd9.MEDIS_PROSEDUR_ICD9, DSL.name("PK_MEDIS_PROSEDUR_ICD9"), new TableField[] { MedisProsedurIcd9.MEDIS_PROSEDUR_ICD9.ID }, true);
    public static final UniqueKey<SupportPenjaminRecord> PK_SUPPORT_PENJAMIN = Internal.createUniqueKey(SupportPenjamin.SUPPORT_PENJAMIN, DSL.name("PK_SUPPORT_PENJAMIN"), new TableField[] { SupportPenjamin.SUPPORT_PENJAMIN.ID }, true);
    public static final UniqueKey<WilayahKabKotaRecord> PK_WILAYAH_KAB_KOTA = Internal.createUniqueKey(WilayahKabKota.WILAYAH_KAB_KOTA, DSL.name("PK_WILAYAH_KAB_KOTA"), new TableField[] { WilayahKabKota.WILAYAH_KAB_KOTA.ID }, true);
    public static final UniqueKey<WilayahKecamatanRecord> PK_WILAYAH_KECAMATAN = Internal.createUniqueKey(WilayahKecamatan.WILAYAH_KECAMATAN, DSL.name("PK_WILAYAH_KECAMATAN"), new TableField[] { WilayahKecamatan.WILAYAH_KECAMATAN.ID }, true);
    public static final UniqueKey<WilayahKelurahanRecord> PK_WILAYAH_KELURAHAN = Internal.createUniqueKey(WilayahKelurahan.WILAYAH_KELURAHAN, DSL.name("PK_WILAYAH_KELURAHAN"), new TableField[] { WilayahKelurahan.WILAYAH_KELURAHAN.ID }, true);
    public static final UniqueKey<WilayahProvinsiRecord> PK_WILAYAH_PROVINSI = Internal.createUniqueKey(WilayahProvinsi.WILAYAH_PROVINSI, DSL.name("PK_WILAYAH_PROVINSI"), new TableField[] { WilayahProvinsi.WILAYAH_PROVINSI.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<WilayahKabKotaRecord, WilayahProvinsiRecord> FK_PROVINSI_ID = Internal.createForeignKey(WilayahKabKota.WILAYAH_KAB_KOTA, DSL.name("FK_PROVINSI_ID"), new TableField[] { WilayahKabKota.WILAYAH_KAB_KOTA.PROVINSI_ID }, Keys.PK_WILAYAH_PROVINSI, new TableField[] { WilayahProvinsi.WILAYAH_PROVINSI.ID }, true);
    public static final ForeignKey<WilayahKecamatanRecord, WilayahKabKotaRecord> FK_KAB_KOTA_ID = Internal.createForeignKey(WilayahKecamatan.WILAYAH_KECAMATAN, DSL.name("FK_KAB_KOTA_ID"), new TableField[] { WilayahKecamatan.WILAYAH_KECAMATAN.KAB_KOTA_ID }, Keys.PK_WILAYAH_KAB_KOTA, new TableField[] { WilayahKabKota.WILAYAH_KAB_KOTA.ID }, true);
    public static final ForeignKey<WilayahKelurahanRecord, WilayahKecamatanRecord> FK_KECAMATAN_ID = Internal.createForeignKey(WilayahKelurahan.WILAYAH_KELURAHAN, DSL.name("FK_KECAMATAN_ID"), new TableField[] { WilayahKelurahan.WILAYAH_KELURAHAN.KECAMATAN_ID }, Keys.PK_WILAYAH_KECAMATAN, new TableField[] { WilayahKecamatan.WILAYAH_KECAMATAN.ID }, true);
}
