/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master;


import com.santika.simrs.jooq.DefaultCatalog;
import com.santika.simrs.jooq.master.tables.MedisDiagnosaIcd10;
import com.santika.simrs.jooq.master.tables.MedisPoli;
import com.santika.simrs.jooq.master.tables.MedisProsedurIcd9;
import com.santika.simrs.jooq.master.tables.SupportPenjamin;
import com.santika.simrs.jooq.master.tables.WilayahKabKota;
import com.santika.simrs.jooq.master.tables.WilayahKecamatan;
import com.santika.simrs.jooq.master.tables.WilayahKelurahan;
import com.santika.simrs.jooq.master.tables.WilayahProvinsi;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Master extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>MASTER</code>
     */
    public static final Master MASTER = new Master();

    /**
     * The table <code>MASTER.MEDIS_DIAGNOSA_ICD10</code>.
     */
    public final MedisDiagnosaIcd10 MEDIS_DIAGNOSA_ICD10 = MedisDiagnosaIcd10.MEDIS_DIAGNOSA_ICD10;

    /**
     * The table <code>MASTER.MEDIS_POLI</code>.
     */
    public final MedisPoli MEDIS_POLI = MedisPoli.MEDIS_POLI;

    /**
     * The table <code>MASTER.MEDIS_PROSEDUR_ICD9</code>.
     */
    public final MedisProsedurIcd9 MEDIS_PROSEDUR_ICD9 = MedisProsedurIcd9.MEDIS_PROSEDUR_ICD9;

    /**
     * The table <code>MASTER.SUPPORT_PENJAMIN</code>.
     */
    public final SupportPenjamin SUPPORT_PENJAMIN = SupportPenjamin.SUPPORT_PENJAMIN;

    /**
     * The table <code>MASTER.WILAYAH_KAB_KOTA</code>.
     */
    public final WilayahKabKota WILAYAH_KAB_KOTA = WilayahKabKota.WILAYAH_KAB_KOTA;

    /**
     * The table <code>MASTER.WILAYAH_KECAMATAN</code>.
     */
    public final WilayahKecamatan WILAYAH_KECAMATAN = WilayahKecamatan.WILAYAH_KECAMATAN;

    /**
     * The table <code>MASTER.WILAYAH_KELURAHAN</code>.
     */
    public final WilayahKelurahan WILAYAH_KELURAHAN = WilayahKelurahan.WILAYAH_KELURAHAN;

    /**
     * The table <code>MASTER.WILAYAH_PROVINSI</code>.
     */
    public final WilayahProvinsi WILAYAH_PROVINSI = WilayahProvinsi.WILAYAH_PROVINSI;

    /**
     * No further instances allowed
     */
    private Master() {
        super("MASTER", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            MedisDiagnosaIcd10.MEDIS_DIAGNOSA_ICD10,
            MedisPoli.MEDIS_POLI,
            MedisProsedurIcd9.MEDIS_PROSEDUR_ICD9,
            SupportPenjamin.SUPPORT_PENJAMIN,
            WilayahKabKota.WILAYAH_KAB_KOTA,
            WilayahKecamatan.WILAYAH_KECAMATAN,
            WilayahKelurahan.WILAYAH_KELURAHAN,
            WilayahProvinsi.WILAYAH_PROVINSI
        );
    }
}
