/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master;


import com.santika.simrs.jooq.master.tables.MedisDiagnosaIcd10;
import com.santika.simrs.jooq.master.tables.MedisPoli;
import com.santika.simrs.jooq.master.tables.MedisProsedurIcd9;
import com.santika.simrs.jooq.master.tables.SupportPenjamin;
import com.santika.simrs.jooq.master.tables.WilayahKabKota;
import com.santika.simrs.jooq.master.tables.WilayahKecamatan;
import com.santika.simrs.jooq.master.tables.WilayahKelurahan;
import com.santika.simrs.jooq.master.tables.WilayahProvinsi;


/**
 * Convenience access to all tables in MASTER.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>MASTER.MEDIS_DIAGNOSA_ICD10</code>.
     */
    public static final MedisDiagnosaIcd10 MEDIS_DIAGNOSA_ICD10 = MedisDiagnosaIcd10.MEDIS_DIAGNOSA_ICD10;

    /**
     * The table <code>MASTER.MEDIS_POLI</code>.
     */
    public static final MedisPoli MEDIS_POLI = MedisPoli.MEDIS_POLI;

    /**
     * The table <code>MASTER.MEDIS_PROSEDUR_ICD9</code>.
     */
    public static final MedisProsedurIcd9 MEDIS_PROSEDUR_ICD9 = MedisProsedurIcd9.MEDIS_PROSEDUR_ICD9;

    /**
     * The table <code>MASTER.SUPPORT_PENJAMIN</code>.
     */
    public static final SupportPenjamin SUPPORT_PENJAMIN = SupportPenjamin.SUPPORT_PENJAMIN;

    /**
     * The table <code>MASTER.WILAYAH_KAB_KOTA</code>.
     */
    public static final WilayahKabKota WILAYAH_KAB_KOTA = WilayahKabKota.WILAYAH_KAB_KOTA;

    /**
     * The table <code>MASTER.WILAYAH_KECAMATAN</code>.
     */
    public static final WilayahKecamatan WILAYAH_KECAMATAN = WilayahKecamatan.WILAYAH_KECAMATAN;

    /**
     * The table <code>MASTER.WILAYAH_KELURAHAN</code>.
     */
    public static final WilayahKelurahan WILAYAH_KELURAHAN = WilayahKelurahan.WILAYAH_KELURAHAN;

    /**
     * The table <code>MASTER.WILAYAH_PROVINSI</code>.
     */
    public static final WilayahProvinsi WILAYAH_PROVINSI = WilayahProvinsi.WILAYAH_PROVINSI;
}
