/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables;


import com.santika.simrs.jooq.master.Keys;
import com.santika.simrs.jooq.master.Master;
import com.santika.simrs.jooq.master.tables.records.MedisPoliRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedisPoli extends TableImpl<MedisPoliRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>MASTER.MEDIS_POLI</code>
     */
    public static final MedisPoli MEDIS_POLI = new MedisPoli();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MedisPoliRecord> getRecordType() {
        return MedisPoliRecord.class;
    }

    /**
     * The column <code>MASTER.MEDIS_POLI.ID</code>.
     */
    public final TableField<MedisPoliRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>MASTER.MEDIS_POLI.KODE_POLI</code>.
     */
    public final TableField<MedisPoliRecord, String> KODE_POLI = createField(DSL.name("KODE_POLI"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>MASTER.MEDIS_POLI.NAMA_POLI</code>.
     */
    public final TableField<MedisPoliRecord, String> NAMA_POLI = createField(DSL.name("NAMA_POLI"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>MASTER.MEDIS_POLI.DELETED_AT</code>.
     */
    public final TableField<MedisPoliRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.MEDIS_POLI.CREATED_AT</code>.
     */
    public final TableField<MedisPoliRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.MEDIS_POLI.UPDATED_AT</code>.
     */
    public final TableField<MedisPoliRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private MedisPoli(Name alias, Table<MedisPoliRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MedisPoli(Name alias, Table<MedisPoliRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>MASTER.MEDIS_POLI</code> table reference
     */
    public MedisPoli(String alias) {
        this(DSL.name(alias), MEDIS_POLI);
    }

    /**
     * Create an aliased <code>MASTER.MEDIS_POLI</code> table reference
     */
    public MedisPoli(Name alias) {
        this(alias, MEDIS_POLI);
    }

    /**
     * Create a <code>MASTER.MEDIS_POLI</code> table reference
     */
    public MedisPoli() {
        this(DSL.name("MEDIS_POLI"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Master.MASTER;
    }

    @Override
    public UniqueKey<MedisPoliRecord> getPrimaryKey() {
        return Keys.PK_MEDIS_POLI;
    }

    @Override
    public MedisPoli as(String alias) {
        return new MedisPoli(DSL.name(alias), this);
    }

    @Override
    public MedisPoli as(Name alias) {
        return new MedisPoli(alias, this);
    }

    @Override
    public MedisPoli as(Table<?> alias) {
        return new MedisPoli(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MedisPoli rename(String name) {
        return new MedisPoli(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedisPoli rename(Name name) {
        return new MedisPoli(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedisPoli rename(Table<?> name) {
        return new MedisPoli(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisPoli where(Condition condition) {
        return new MedisPoli(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisPoli where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisPoli where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisPoli where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedisPoli where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedisPoli where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedisPoli where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedisPoli where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisPoli whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisPoli whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
