/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables;


import com.santika.simrs.jooq.master.Keys;
import com.santika.simrs.jooq.master.Master;
import com.santika.simrs.jooq.master.tables.records.MedisProsedurIcd9Record;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedisProsedurIcd9 extends TableImpl<MedisProsedurIcd9Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>MASTER.MEDIS_PROSEDUR_ICD9</code>
     */
    public static final MedisProsedurIcd9 MEDIS_PROSEDUR_ICD9 = new MedisProsedurIcd9();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MedisProsedurIcd9Record> getRecordType() {
        return MedisProsedurIcd9Record.class;
    }

    /**
     * The column <code>MASTER.MEDIS_PROSEDUR_ICD9.ID</code>.
     */
    public final TableField<MedisProsedurIcd9Record, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>MASTER.MEDIS_PROSEDUR_ICD9.KODE_PROSEDUR</code>.
     */
    public final TableField<MedisProsedurIcd9Record, String> KODE_PROSEDUR = createField(DSL.name("KODE_PROSEDUR"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>MASTER.MEDIS_PROSEDUR_ICD9.NAMA_PROSEDUR</code>.
     */
    public final TableField<MedisProsedurIcd9Record, String> NAMA_PROSEDUR = createField(DSL.name("NAMA_PROSEDUR"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>MASTER.MEDIS_PROSEDUR_ICD9.DELETED_AT</code>.
     */
    public final TableField<MedisProsedurIcd9Record, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.MEDIS_PROSEDUR_ICD9.CREATED_AT</code>.
     */
    public final TableField<MedisProsedurIcd9Record, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.MEDIS_PROSEDUR_ICD9.UPDATED_AT</code>.
     */
    public final TableField<MedisProsedurIcd9Record, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private MedisProsedurIcd9(Name alias, Table<MedisProsedurIcd9Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MedisProsedurIcd9(Name alias, Table<MedisProsedurIcd9Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>MASTER.MEDIS_PROSEDUR_ICD9</code> table reference
     */
    public MedisProsedurIcd9(String alias) {
        this(DSL.name(alias), MEDIS_PROSEDUR_ICD9);
    }

    /**
     * Create an aliased <code>MASTER.MEDIS_PROSEDUR_ICD9</code> table reference
     */
    public MedisProsedurIcd9(Name alias) {
        this(alias, MEDIS_PROSEDUR_ICD9);
    }

    /**
     * Create a <code>MASTER.MEDIS_PROSEDUR_ICD9</code> table reference
     */
    public MedisProsedurIcd9() {
        this(DSL.name("MEDIS_PROSEDUR_ICD9"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Master.MASTER;
    }

    @Override
    public UniqueKey<MedisProsedurIcd9Record> getPrimaryKey() {
        return Keys.PK_MEDIS_PROSEDUR_ICD9;
    }

    @Override
    public MedisProsedurIcd9 as(String alias) {
        return new MedisProsedurIcd9(DSL.name(alias), this);
    }

    @Override
    public MedisProsedurIcd9 as(Name alias) {
        return new MedisProsedurIcd9(alias, this);
    }

    @Override
    public MedisProsedurIcd9 as(Table<?> alias) {
        return new MedisProsedurIcd9(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MedisProsedurIcd9 rename(String name) {
        return new MedisProsedurIcd9(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedisProsedurIcd9 rename(Name name) {
        return new MedisProsedurIcd9(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedisProsedurIcd9 rename(Table<?> name) {
        return new MedisProsedurIcd9(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisProsedurIcd9 where(Condition condition) {
        return new MedisProsedurIcd9(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisProsedurIcd9 where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisProsedurIcd9 where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisProsedurIcd9 where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedisProsedurIcd9 where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedisProsedurIcd9 where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedisProsedurIcd9 where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedisProsedurIcd9 where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisProsedurIcd9 whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisProsedurIcd9 whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
