/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables;


import com.santika.simrs.jooq.master.Keys;
import com.santika.simrs.jooq.master.Master;
import com.santika.simrs.jooq.master.tables.records.MedisDiagnosaIcd10Record;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MedisDiagnosaIcd10 extends TableImpl<MedisDiagnosaIcd10Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>MASTER.MEDIS_DIAGNOSA_ICD10</code>
     */
    public static final MedisDiagnosaIcd10 MEDIS_DIAGNOSA_ICD10 = new MedisDiagnosaIcd10();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MedisDiagnosaIcd10Record> getRecordType() {
        return MedisDiagnosaIcd10Record.class;
    }

    /**
     * The column <code>MASTER.MEDIS_DIAGNOSA_ICD10.ID</code>.
     */
    public final TableField<MedisDiagnosaIcd10Record, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>MASTER.MEDIS_DIAGNOSA_ICD10.KODE_DIAGNOSA</code>.
     */
    public final TableField<MedisDiagnosaIcd10Record, String> KODE_DIAGNOSA = createField(DSL.name("KODE_DIAGNOSA"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>MASTER.MEDIS_DIAGNOSA_ICD10.NAMA_DIAGNOSA</code>.
     */
    public final TableField<MedisDiagnosaIcd10Record, String> NAMA_DIAGNOSA = createField(DSL.name("NAMA_DIAGNOSA"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>MASTER.MEDIS_DIAGNOSA_ICD10.DELETED_AT</code>.
     */
    public final TableField<MedisDiagnosaIcd10Record, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.MEDIS_DIAGNOSA_ICD10.CREATED_AT</code>.
     */
    public final TableField<MedisDiagnosaIcd10Record, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.MEDIS_DIAGNOSA_ICD10.UPDATED_AT</code>.
     */
    public final TableField<MedisDiagnosaIcd10Record, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private MedisDiagnosaIcd10(Name alias, Table<MedisDiagnosaIcd10Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MedisDiagnosaIcd10(Name alias, Table<MedisDiagnosaIcd10Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>MASTER.MEDIS_DIAGNOSA_ICD10</code> table
     * reference
     */
    public MedisDiagnosaIcd10(String alias) {
        this(DSL.name(alias), MEDIS_DIAGNOSA_ICD10);
    }

    /**
     * Create an aliased <code>MASTER.MEDIS_DIAGNOSA_ICD10</code> table
     * reference
     */
    public MedisDiagnosaIcd10(Name alias) {
        this(alias, MEDIS_DIAGNOSA_ICD10);
    }

    /**
     * Create a <code>MASTER.MEDIS_DIAGNOSA_ICD10</code> table reference
     */
    public MedisDiagnosaIcd10() {
        this(DSL.name("MEDIS_DIAGNOSA_ICD10"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Master.MASTER;
    }

    @Override
    public UniqueKey<MedisDiagnosaIcd10Record> getPrimaryKey() {
        return Keys.PK_MEDIS_DIAGNOSA_ICD10;
    }

    @Override
    public MedisDiagnosaIcd10 as(String alias) {
        return new MedisDiagnosaIcd10(DSL.name(alias), this);
    }

    @Override
    public MedisDiagnosaIcd10 as(Name alias) {
        return new MedisDiagnosaIcd10(alias, this);
    }

    @Override
    public MedisDiagnosaIcd10 as(Table<?> alias) {
        return new MedisDiagnosaIcd10(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MedisDiagnosaIcd10 rename(String name) {
        return new MedisDiagnosaIcd10(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedisDiagnosaIcd10 rename(Name name) {
        return new MedisDiagnosaIcd10(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MedisDiagnosaIcd10 rename(Table<?> name) {
        return new MedisDiagnosaIcd10(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisDiagnosaIcd10 where(Condition condition) {
        return new MedisDiagnosaIcd10(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisDiagnosaIcd10 where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisDiagnosaIcd10 where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisDiagnosaIcd10 where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedisDiagnosaIcd10 where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedisDiagnosaIcd10 where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedisDiagnosaIcd10 where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MedisDiagnosaIcd10 where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisDiagnosaIcd10 whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MedisDiagnosaIcd10 whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
