/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables;


import com.santika.simrs.jooq.master.Keys;
import com.santika.simrs.jooq.master.Master;
import com.santika.simrs.jooq.master.tables.records.SupportPenjaminRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SupportPenjamin extends TableImpl<SupportPenjaminRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>MASTER.SUPPORT_PENJAMIN</code>
     */
    public static final SupportPenjamin SUPPORT_PENJAMIN = new SupportPenjamin();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SupportPenjaminRecord> getRecordType() {
        return SupportPenjaminRecord.class;
    }

    /**
     * The column <code>MASTER.SUPPORT_PENJAMIN.ID</code>.
     */
    public final TableField<SupportPenjaminRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>MASTER.SUPPORT_PENJAMIN.PENJAMIN</code>.
     */
    public final TableField<SupportPenjaminRecord, String> PENJAMIN = createField(DSL.name("PENJAMIN"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>MASTER.SUPPORT_PENJAMIN.NAMA_PERUSAHAAN_PENJAMIN</code>.
     */
    public final TableField<SupportPenjaminRecord, String> NAMA_PERUSAHAAN_PENJAMIN = createField(DSL.name("NAMA_PERUSAHAAN_PENJAMIN"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>MASTER.SUPPORT_PENJAMIN.ALAMAT_PENJAMIN</code>.
     */
    public final TableField<SupportPenjaminRecord, String> ALAMAT_PENJAMIN = createField(DSL.name("ALAMAT_PENJAMIN"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>MASTER.SUPPORT_PENJAMIN.TELEPON_PENJAMIN</code>.
     */
    public final TableField<SupportPenjaminRecord, String> TELEPON_PENJAMIN = createField(DSL.name("TELEPON_PENJAMIN"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>MASTER.SUPPORT_PENJAMIN.PENERIMA_TAGIHAN</code>.
     */
    public final TableField<SupportPenjaminRecord, String> PENERIMA_TAGIHAN = createField(DSL.name("PENERIMA_TAGIHAN"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>MASTER.SUPPORT_PENJAMIN.IS_ACTIVE</code>.
     */
    public final TableField<SupportPenjaminRecord, Boolean> IS_ACTIVE = createField(DSL.name("IS_ACTIVE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("TRUE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>MASTER.SUPPORT_PENJAMIN.DELETED_AT</code>.
     */
    public final TableField<SupportPenjaminRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.SUPPORT_PENJAMIN.CREATED_AT</code>.
     */
    public final TableField<SupportPenjaminRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.SUPPORT_PENJAMIN.UPDATED_AT</code>.
     */
    public final TableField<SupportPenjaminRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private SupportPenjamin(Name alias, Table<SupportPenjaminRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SupportPenjamin(Name alias, Table<SupportPenjaminRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>MASTER.SUPPORT_PENJAMIN</code> table reference
     */
    public SupportPenjamin(String alias) {
        this(DSL.name(alias), SUPPORT_PENJAMIN);
    }

    /**
     * Create an aliased <code>MASTER.SUPPORT_PENJAMIN</code> table reference
     */
    public SupportPenjamin(Name alias) {
        this(alias, SUPPORT_PENJAMIN);
    }

    /**
     * Create a <code>MASTER.SUPPORT_PENJAMIN</code> table reference
     */
    public SupportPenjamin() {
        this(DSL.name("SUPPORT_PENJAMIN"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Master.MASTER;
    }

    @Override
    public UniqueKey<SupportPenjaminRecord> getPrimaryKey() {
        return Keys.PK_SUPPORT_PENJAMIN;
    }

    @Override
    public SupportPenjamin as(String alias) {
        return new SupportPenjamin(DSL.name(alias), this);
    }

    @Override
    public SupportPenjamin as(Name alias) {
        return new SupportPenjamin(alias, this);
    }

    @Override
    public SupportPenjamin as(Table<?> alias) {
        return new SupportPenjamin(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SupportPenjamin rename(String name) {
        return new SupportPenjamin(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupportPenjamin rename(Name name) {
        return new SupportPenjamin(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SupportPenjamin rename(Table<?> name) {
        return new SupportPenjamin(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SupportPenjamin where(Condition condition) {
        return new SupportPenjamin(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SupportPenjamin where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SupportPenjamin where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SupportPenjamin where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SupportPenjamin where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SupportPenjamin where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SupportPenjamin where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SupportPenjamin where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SupportPenjamin whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SupportPenjamin whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
