/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables;


import com.santika.simrs.jooq.master.Keys;
import com.santika.simrs.jooq.master.Master;
import com.santika.simrs.jooq.master.tables.WilayahKabKota.WilayahKabKotaPath;
import com.santika.simrs.jooq.master.tables.records.WilayahProvinsiRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WilayahProvinsi extends TableImpl<WilayahProvinsiRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>MASTER.WILAYAH_PROVINSI</code>
     */
    public static final WilayahProvinsi WILAYAH_PROVINSI = new WilayahProvinsi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WilayahProvinsiRecord> getRecordType() {
        return WilayahProvinsiRecord.class;
    }

    /**
     * The column <code>MASTER.WILAYAH_PROVINSI.ID</code>.
     */
    public final TableField<WilayahProvinsiRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>MASTER.WILAYAH_PROVINSI.KODE_PROVINSI</code>.
     */
    public final TableField<WilayahProvinsiRecord, String> KODE_PROVINSI = createField(DSL.name("KODE_PROVINSI"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>MASTER.WILAYAH_PROVINSI.NAMA_PROVINSI</code>.
     */
    public final TableField<WilayahProvinsiRecord, String> NAMA_PROVINSI = createField(DSL.name("NAMA_PROVINSI"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>MASTER.WILAYAH_PROVINSI.DELETED_AT</code>.
     */
    public final TableField<WilayahProvinsiRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.WILAYAH_PROVINSI.CREATED_AT</code>.
     */
    public final TableField<WilayahProvinsiRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.WILAYAH_PROVINSI.UPDATED_AT</code>.
     */
    public final TableField<WilayahProvinsiRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private WilayahProvinsi(Name alias, Table<WilayahProvinsiRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WilayahProvinsi(Name alias, Table<WilayahProvinsiRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>MASTER.WILAYAH_PROVINSI</code> table reference
     */
    public WilayahProvinsi(String alias) {
        this(DSL.name(alias), WILAYAH_PROVINSI);
    }

    /**
     * Create an aliased <code>MASTER.WILAYAH_PROVINSI</code> table reference
     */
    public WilayahProvinsi(Name alias) {
        this(alias, WILAYAH_PROVINSI);
    }

    /**
     * Create a <code>MASTER.WILAYAH_PROVINSI</code> table reference
     */
    public WilayahProvinsi() {
        this(DSL.name("WILAYAH_PROVINSI"), null);
    }

    public <O extends Record> WilayahProvinsi(Table<O> path, ForeignKey<O, WilayahProvinsiRecord> childPath, InverseForeignKey<O, WilayahProvinsiRecord> parentPath) {
        super(path, childPath, parentPath, WILAYAH_PROVINSI);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WilayahProvinsiPath extends WilayahProvinsi implements Path<WilayahProvinsiRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WilayahProvinsiPath(Table<O> path, ForeignKey<O, WilayahProvinsiRecord> childPath, InverseForeignKey<O, WilayahProvinsiRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WilayahProvinsiPath(Name alias, Table<WilayahProvinsiRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WilayahProvinsiPath as(String alias) {
            return new WilayahProvinsiPath(DSL.name(alias), this);
        }

        @Override
        public WilayahProvinsiPath as(Name alias) {
            return new WilayahProvinsiPath(alias, this);
        }

        @Override
        public WilayahProvinsiPath as(Table<?> alias) {
            return new WilayahProvinsiPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Master.MASTER;
    }

    @Override
    public UniqueKey<WilayahProvinsiRecord> getPrimaryKey() {
        return Keys.PK_WILAYAH_PROVINSI;
    }

    private transient WilayahKabKotaPath _wilayahKabKota;

    /**
     * Get the implicit to-many join path to the
     * <code>MASTER.WILAYAH_KAB_KOTA</code> table
     */
    public WilayahKabKotaPath wilayahKabKota() {
        if (_wilayahKabKota == null)
            _wilayahKabKota = new WilayahKabKotaPath(this, null, Keys.FK_PROVINSI_ID.getInverseKey());

        return _wilayahKabKota;
    }

    @Override
    public WilayahProvinsi as(String alias) {
        return new WilayahProvinsi(DSL.name(alias), this);
    }

    @Override
    public WilayahProvinsi as(Name alias) {
        return new WilayahProvinsi(alias, this);
    }

    @Override
    public WilayahProvinsi as(Table<?> alias) {
        return new WilayahProvinsi(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WilayahProvinsi rename(String name) {
        return new WilayahProvinsi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WilayahProvinsi rename(Name name) {
        return new WilayahProvinsi(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WilayahProvinsi rename(Table<?> name) {
        return new WilayahProvinsi(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahProvinsi where(Condition condition) {
        return new WilayahProvinsi(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahProvinsi where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahProvinsi where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahProvinsi where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahProvinsi where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahProvinsi where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahProvinsi where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahProvinsi where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahProvinsi whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahProvinsi whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
