/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables;


import com.santika.simrs.jooq.master.Keys;
import com.santika.simrs.jooq.master.Master;
import com.santika.simrs.jooq.master.tables.WilayahKecamatan.WilayahKecamatanPath;
import com.santika.simrs.jooq.master.tables.records.WilayahKelurahanRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WilayahKelurahan extends TableImpl<WilayahKelurahanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>MASTER.WILAYAH_KELURAHAN</code>
     */
    public static final WilayahKelurahan WILAYAH_KELURAHAN = new WilayahKelurahan();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WilayahKelurahanRecord> getRecordType() {
        return WilayahKelurahanRecord.class;
    }

    /**
     * The column <code>MASTER.WILAYAH_KELURAHAN.ID</code>.
     */
    public final TableField<WilayahKelurahanRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KELURAHAN.KECAMATAN_ID</code>.
     */
    public final TableField<WilayahKelurahanRecord, UUID> KECAMATAN_ID = createField(DSL.name("KECAMATAN_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KELURAHAN.KODE_KELURAHAN</code>.
     */
    public final TableField<WilayahKelurahanRecord, String> KODE_KELURAHAN = createField(DSL.name("KODE_KELURAHAN"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KELURAHAN.NAMA_KELURAHAN</code>.
     */
    public final TableField<WilayahKelurahanRecord, String> NAMA_KELURAHAN = createField(DSL.name("NAMA_KELURAHAN"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KELURAHAN.DELETED_AT</code>.
     */
    public final TableField<WilayahKelurahanRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KELURAHAN.CREATED_AT</code>.
     */
    public final TableField<WilayahKelurahanRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KELURAHAN.UPDATED_AT</code>.
     */
    public final TableField<WilayahKelurahanRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private WilayahKelurahan(Name alias, Table<WilayahKelurahanRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WilayahKelurahan(Name alias, Table<WilayahKelurahanRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>MASTER.WILAYAH_KELURAHAN</code> table reference
     */
    public WilayahKelurahan(String alias) {
        this(DSL.name(alias), WILAYAH_KELURAHAN);
    }

    /**
     * Create an aliased <code>MASTER.WILAYAH_KELURAHAN</code> table reference
     */
    public WilayahKelurahan(Name alias) {
        this(alias, WILAYAH_KELURAHAN);
    }

    /**
     * Create a <code>MASTER.WILAYAH_KELURAHAN</code> table reference
     */
    public WilayahKelurahan() {
        this(DSL.name("WILAYAH_KELURAHAN"), null);
    }

    public <O extends Record> WilayahKelurahan(Table<O> path, ForeignKey<O, WilayahKelurahanRecord> childPath, InverseForeignKey<O, WilayahKelurahanRecord> parentPath) {
        super(path, childPath, parentPath, WILAYAH_KELURAHAN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WilayahKelurahanPath extends WilayahKelurahan implements Path<WilayahKelurahanRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WilayahKelurahanPath(Table<O> path, ForeignKey<O, WilayahKelurahanRecord> childPath, InverseForeignKey<O, WilayahKelurahanRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WilayahKelurahanPath(Name alias, Table<WilayahKelurahanRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WilayahKelurahanPath as(String alias) {
            return new WilayahKelurahanPath(DSL.name(alias), this);
        }

        @Override
        public WilayahKelurahanPath as(Name alias) {
            return new WilayahKelurahanPath(alias, this);
        }

        @Override
        public WilayahKelurahanPath as(Table<?> alias) {
            return new WilayahKelurahanPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Master.MASTER;
    }

    @Override
    public UniqueKey<WilayahKelurahanRecord> getPrimaryKey() {
        return Keys.PK_WILAYAH_KELURAHAN;
    }

    @Override
    public List<ForeignKey<WilayahKelurahanRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_KECAMATAN_ID);
    }

    private transient WilayahKecamatanPath _wilayahKecamatan;

    /**
     * Get the implicit join path to the <code>MASTER.WILAYAH_KECAMATAN</code>
     * table.
     */
    public WilayahKecamatanPath wilayahKecamatan() {
        if (_wilayahKecamatan == null)
            _wilayahKecamatan = new WilayahKecamatanPath(this, Keys.FK_KECAMATAN_ID, null);

        return _wilayahKecamatan;
    }

    @Override
    public WilayahKelurahan as(String alias) {
        return new WilayahKelurahan(DSL.name(alias), this);
    }

    @Override
    public WilayahKelurahan as(Name alias) {
        return new WilayahKelurahan(alias, this);
    }

    @Override
    public WilayahKelurahan as(Table<?> alias) {
        return new WilayahKelurahan(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WilayahKelurahan rename(String name) {
        return new WilayahKelurahan(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WilayahKelurahan rename(Name name) {
        return new WilayahKelurahan(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WilayahKelurahan rename(Table<?> name) {
        return new WilayahKelurahan(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKelurahan where(Condition condition) {
        return new WilayahKelurahan(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKelurahan where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKelurahan where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKelurahan where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahKelurahan where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahKelurahan where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahKelurahan where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahKelurahan where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKelurahan whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKelurahan whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
