/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables;


import com.santika.simrs.jooq.master.Keys;
import com.santika.simrs.jooq.master.Master;
import com.santika.simrs.jooq.master.tables.WilayahKabKota.WilayahKabKotaPath;
import com.santika.simrs.jooq.master.tables.WilayahKelurahan.WilayahKelurahanPath;
import com.santika.simrs.jooq.master.tables.records.WilayahKecamatanRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WilayahKecamatan extends TableImpl<WilayahKecamatanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>MASTER.WILAYAH_KECAMATAN</code>
     */
    public static final WilayahKecamatan WILAYAH_KECAMATAN = new WilayahKecamatan();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WilayahKecamatanRecord> getRecordType() {
        return WilayahKecamatanRecord.class;
    }

    /**
     * The column <code>MASTER.WILAYAH_KECAMATAN.ID</code>.
     */
    public final TableField<WilayahKecamatanRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KECAMATAN.KAB_KOTA_ID</code>.
     */
    public final TableField<WilayahKecamatanRecord, UUID> KAB_KOTA_ID = createField(DSL.name("KAB_KOTA_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KECAMATAN.KODE_KECAMATAN</code>.
     */
    public final TableField<WilayahKecamatanRecord, String> KODE_KECAMATAN = createField(DSL.name("KODE_KECAMATAN"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KECAMATAN.NAMA_KECAMATAN</code>.
     */
    public final TableField<WilayahKecamatanRecord, String> NAMA_KECAMATAN = createField(DSL.name("NAMA_KECAMATAN"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KECAMATAN.DELETED_AT</code>.
     */
    public final TableField<WilayahKecamatanRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KECAMATAN.CREATED_AT</code>.
     */
    public final TableField<WilayahKecamatanRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KECAMATAN.UPDATED_AT</code>.
     */
    public final TableField<WilayahKecamatanRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private WilayahKecamatan(Name alias, Table<WilayahKecamatanRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WilayahKecamatan(Name alias, Table<WilayahKecamatanRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>MASTER.WILAYAH_KECAMATAN</code> table reference
     */
    public WilayahKecamatan(String alias) {
        this(DSL.name(alias), WILAYAH_KECAMATAN);
    }

    /**
     * Create an aliased <code>MASTER.WILAYAH_KECAMATAN</code> table reference
     */
    public WilayahKecamatan(Name alias) {
        this(alias, WILAYAH_KECAMATAN);
    }

    /**
     * Create a <code>MASTER.WILAYAH_KECAMATAN</code> table reference
     */
    public WilayahKecamatan() {
        this(DSL.name("WILAYAH_KECAMATAN"), null);
    }

    public <O extends Record> WilayahKecamatan(Table<O> path, ForeignKey<O, WilayahKecamatanRecord> childPath, InverseForeignKey<O, WilayahKecamatanRecord> parentPath) {
        super(path, childPath, parentPath, WILAYAH_KECAMATAN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WilayahKecamatanPath extends WilayahKecamatan implements Path<WilayahKecamatanRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WilayahKecamatanPath(Table<O> path, ForeignKey<O, WilayahKecamatanRecord> childPath, InverseForeignKey<O, WilayahKecamatanRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WilayahKecamatanPath(Name alias, Table<WilayahKecamatanRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WilayahKecamatanPath as(String alias) {
            return new WilayahKecamatanPath(DSL.name(alias), this);
        }

        @Override
        public WilayahKecamatanPath as(Name alias) {
            return new WilayahKecamatanPath(alias, this);
        }

        @Override
        public WilayahKecamatanPath as(Table<?> alias) {
            return new WilayahKecamatanPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Master.MASTER;
    }

    @Override
    public UniqueKey<WilayahKecamatanRecord> getPrimaryKey() {
        return Keys.PK_WILAYAH_KECAMATAN;
    }

    @Override
    public List<ForeignKey<WilayahKecamatanRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_KAB_KOTA_ID);
    }

    private transient WilayahKabKotaPath _wilayahKabKota;

    /**
     * Get the implicit join path to the <code>MASTER.WILAYAH_KAB_KOTA</code>
     * table.
     */
    public WilayahKabKotaPath wilayahKabKota() {
        if (_wilayahKabKota == null)
            _wilayahKabKota = new WilayahKabKotaPath(this, Keys.FK_KAB_KOTA_ID, null);

        return _wilayahKabKota;
    }

    private transient WilayahKelurahanPath _wilayahKelurahan;

    /**
     * Get the implicit to-many join path to the
     * <code>MASTER.WILAYAH_KELURAHAN</code> table
     */
    public WilayahKelurahanPath wilayahKelurahan() {
        if (_wilayahKelurahan == null)
            _wilayahKelurahan = new WilayahKelurahanPath(this, null, Keys.FK_KECAMATAN_ID.getInverseKey());

        return _wilayahKelurahan;
    }

    @Override
    public WilayahKecamatan as(String alias) {
        return new WilayahKecamatan(DSL.name(alias), this);
    }

    @Override
    public WilayahKecamatan as(Name alias) {
        return new WilayahKecamatan(alias, this);
    }

    @Override
    public WilayahKecamatan as(Table<?> alias) {
        return new WilayahKecamatan(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WilayahKecamatan rename(String name) {
        return new WilayahKecamatan(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WilayahKecamatan rename(Name name) {
        return new WilayahKecamatan(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WilayahKecamatan rename(Table<?> name) {
        return new WilayahKecamatan(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKecamatan where(Condition condition) {
        return new WilayahKecamatan(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKecamatan where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKecamatan where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKecamatan where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahKecamatan where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahKecamatan where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahKecamatan where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahKecamatan where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKecamatan whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKecamatan whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
