/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.master.tables;


import com.santika.simrs.jooq.master.Keys;
import com.santika.simrs.jooq.master.Master;
import com.santika.simrs.jooq.master.tables.WilayahKecamatan.WilayahKecamatanPath;
import com.santika.simrs.jooq.master.tables.WilayahProvinsi.WilayahProvinsiPath;
import com.santika.simrs.jooq.master.tables.records.WilayahKabKotaRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WilayahKabKota extends TableImpl<WilayahKabKotaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>MASTER.WILAYAH_KAB_KOTA</code>
     */
    public static final WilayahKabKota WILAYAH_KAB_KOTA = new WilayahKabKota();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WilayahKabKotaRecord> getRecordType() {
        return WilayahKabKotaRecord.class;
    }

    /**
     * The column <code>MASTER.WILAYAH_KAB_KOTA.ID</code>.
     */
    public final TableField<WilayahKabKotaRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KAB_KOTA.PROVINSI_ID</code>.
     */
    public final TableField<WilayahKabKotaRecord, UUID> PROVINSI_ID = createField(DSL.name("PROVINSI_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KAB_KOTA.KODE_KAB_KOTA</code>.
     */
    public final TableField<WilayahKabKotaRecord, String> KODE_KAB_KOTA = createField(DSL.name("KODE_KAB_KOTA"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KAB_KOTA.NAMA_KAB_KOTA</code>.
     */
    public final TableField<WilayahKabKotaRecord, String> NAMA_KAB_KOTA = createField(DSL.name("NAMA_KAB_KOTA"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KAB_KOTA.DELETED_AT</code>.
     */
    public final TableField<WilayahKabKotaRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KAB_KOTA.CREATED_AT</code>.
     */
    public final TableField<WilayahKabKotaRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>MASTER.WILAYAH_KAB_KOTA.UPDATED_AT</code>.
     */
    public final TableField<WilayahKabKotaRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private WilayahKabKota(Name alias, Table<WilayahKabKotaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WilayahKabKota(Name alias, Table<WilayahKabKotaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>MASTER.WILAYAH_KAB_KOTA</code> table reference
     */
    public WilayahKabKota(String alias) {
        this(DSL.name(alias), WILAYAH_KAB_KOTA);
    }

    /**
     * Create an aliased <code>MASTER.WILAYAH_KAB_KOTA</code> table reference
     */
    public WilayahKabKota(Name alias) {
        this(alias, WILAYAH_KAB_KOTA);
    }

    /**
     * Create a <code>MASTER.WILAYAH_KAB_KOTA</code> table reference
     */
    public WilayahKabKota() {
        this(DSL.name("WILAYAH_KAB_KOTA"), null);
    }

    public <O extends Record> WilayahKabKota(Table<O> path, ForeignKey<O, WilayahKabKotaRecord> childPath, InverseForeignKey<O, WilayahKabKotaRecord> parentPath) {
        super(path, childPath, parentPath, WILAYAH_KAB_KOTA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WilayahKabKotaPath extends WilayahKabKota implements Path<WilayahKabKotaRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WilayahKabKotaPath(Table<O> path, ForeignKey<O, WilayahKabKotaRecord> childPath, InverseForeignKey<O, WilayahKabKotaRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WilayahKabKotaPath(Name alias, Table<WilayahKabKotaRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WilayahKabKotaPath as(String alias) {
            return new WilayahKabKotaPath(DSL.name(alias), this);
        }

        @Override
        public WilayahKabKotaPath as(Name alias) {
            return new WilayahKabKotaPath(alias, this);
        }

        @Override
        public WilayahKabKotaPath as(Table<?> alias) {
            return new WilayahKabKotaPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Master.MASTER;
    }

    @Override
    public UniqueKey<WilayahKabKotaRecord> getPrimaryKey() {
        return Keys.PK_WILAYAH_KAB_KOTA;
    }

    @Override
    public List<ForeignKey<WilayahKabKotaRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PROVINSI_ID);
    }

    private transient WilayahProvinsiPath _wilayahProvinsi;

    /**
     * Get the implicit join path to the <code>MASTER.WILAYAH_PROVINSI</code>
     * table.
     */
    public WilayahProvinsiPath wilayahProvinsi() {
        if (_wilayahProvinsi == null)
            _wilayahProvinsi = new WilayahProvinsiPath(this, Keys.FK_PROVINSI_ID, null);

        return _wilayahProvinsi;
    }

    private transient WilayahKecamatanPath _wilayahKecamatan;

    /**
     * Get the implicit to-many join path to the
     * <code>MASTER.WILAYAH_KECAMATAN</code> table
     */
    public WilayahKecamatanPath wilayahKecamatan() {
        if (_wilayahKecamatan == null)
            _wilayahKecamatan = new WilayahKecamatanPath(this, null, Keys.FK_KAB_KOTA_ID.getInverseKey());

        return _wilayahKecamatan;
    }

    @Override
    public WilayahKabKota as(String alias) {
        return new WilayahKabKota(DSL.name(alias), this);
    }

    @Override
    public WilayahKabKota as(Name alias) {
        return new WilayahKabKota(alias, this);
    }

    @Override
    public WilayahKabKota as(Table<?> alias) {
        return new WilayahKabKota(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WilayahKabKota rename(String name) {
        return new WilayahKabKota(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WilayahKabKota rename(Name name) {
        return new WilayahKabKota(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WilayahKabKota rename(Table<?> name) {
        return new WilayahKabKota(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKabKota where(Condition condition) {
        return new WilayahKabKota(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKabKota where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKabKota where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKabKota where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahKabKota where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahKabKota where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahKabKota where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WilayahKabKota where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKabKota whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WilayahKabKota whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
