/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared.tables;


import com.santika.simrs.jooq.shared.Keys;
import com.santika.simrs.jooq.shared.Shared;
import com.santika.simrs.jooq.shared.tables.records.AuditRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Audit extends TableImpl<AuditRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SHARED.AUDIT</code>
     */
    public static final Audit AUDIT = new Audit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuditRecord> getRecordType() {
        return AuditRecord.class;
    }

    /**
     * The column <code>SHARED.AUDIT.ID</code>.
     */
    public final TableField<AuditRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>SHARED.AUDIT.USERNAME</code>.
     */
    public final TableField<AuditRecord, String> USERNAME = createField(DSL.name("USERNAME"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>SHARED.AUDIT.ACTION</code>.
     */
    public final TableField<AuditRecord, String> ACTION = createField(DSL.name("ACTION"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>SHARED.AUDIT.PAYLOAD</code>.
     */
    public final TableField<AuditRecord, String> PAYLOAD = createField(DSL.name("PAYLOAD"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>SHARED.AUDIT.TIMESTAMP</code>.
     */
    public final TableField<AuditRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("TIMESTAMP"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("LOCALTIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Audit(Name alias, Table<AuditRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Audit(Name alias, Table<AuditRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SHARED.AUDIT</code> table reference
     */
    public Audit(String alias) {
        this(DSL.name(alias), AUDIT);
    }

    /**
     * Create an aliased <code>SHARED.AUDIT</code> table reference
     */
    public Audit(Name alias) {
        this(alias, AUDIT);
    }

    /**
     * Create a <code>SHARED.AUDIT</code> table reference
     */
    public Audit() {
        this(DSL.name("AUDIT"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Shared.SHARED;
    }

    @Override
    public UniqueKey<AuditRecord> getPrimaryKey() {
        return Keys.PK_AUDIT;
    }

    @Override
    public Audit as(String alias) {
        return new Audit(DSL.name(alias), this);
    }

    @Override
    public Audit as(Name alias) {
        return new Audit(alias, this);
    }

    @Override
    public Audit as(Table<?> alias) {
        return new Audit(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Audit rename(String name) {
        return new Audit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Audit rename(Name name) {
        return new Audit(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Audit rename(Table<?> name) {
        return new Audit(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Audit where(Condition condition) {
        return new Audit(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Audit where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Audit where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Audit where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Audit where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Audit where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Audit where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Audit where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Audit whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Audit whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
