/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared.tables;


import com.santika.simrs.jooq.shared.Keys;
import com.santika.simrs.jooq.shared.Shared;
import com.santika.simrs.jooq.shared.tables.records.FileRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class File extends TableImpl<FileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SHARED.FILE</code>
     */
    public static final File FILE = new File();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FileRecord> getRecordType() {
        return FileRecord.class;
    }

    /**
     * The column <code>SHARED.FILE.ID</code>.
     */
    public final TableField<FileRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>SHARED.FILE.NAME</code>.
     */
    public final TableField<FileRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>SHARED.FILE.PATH</code>.
     */
    public final TableField<FileRecord, String> PATH = createField(DSL.name("PATH"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>SHARED.FILE.SIZE</code>.
     */
    public final TableField<FileRecord, String> SIZE = createField(DSL.name("SIZE"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>SHARED.FILE.EXT</code>.
     */
    public final TableField<FileRecord, String> EXT = createField(DSL.name("EXT"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>SHARED.FILE.MIME_TYPE</code>.
     */
    public final TableField<FileRecord, String> MIME_TYPE = createField(DSL.name("MIME_TYPE"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>SHARED.FILE.TEMP_NAME</code>.
     */
    public final TableField<FileRecord, String> TEMP_NAME = createField(DSL.name("TEMP_NAME"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>SHARED.FILE.IS_TEMP</code>.
     */
    public final TableField<FileRecord, Boolean> IS_TEMP = createField(DSL.name("IS_TEMP"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("TRUE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>SHARED.FILE.DELETED_AT</code>.
     */
    public final TableField<FileRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>SHARED.FILE.CREATED_AT</code>.
     */
    public final TableField<FileRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>SHARED.FILE.UPDATED_AT</code>.
     */
    public final TableField<FileRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private File(Name alias, Table<FileRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private File(Name alias, Table<FileRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SHARED.FILE</code> table reference
     */
    public File(String alias) {
        this(DSL.name(alias), FILE);
    }

    /**
     * Create an aliased <code>SHARED.FILE</code> table reference
     */
    public File(Name alias) {
        this(alias, FILE);
    }

    /**
     * Create a <code>SHARED.FILE</code> table reference
     */
    public File() {
        this(DSL.name("FILE"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Shared.SHARED;
    }

    @Override
    public UniqueKey<FileRecord> getPrimaryKey() {
        return Keys.PK_FILE;
    }

    @Override
    public File as(String alias) {
        return new File(DSL.name(alias), this);
    }

    @Override
    public File as(Name alias) {
        return new File(alias, this);
    }

    @Override
    public File as(Table<?> alias) {
        return new File(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public File rename(String name) {
        return new File(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public File rename(Name name) {
        return new File(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public File rename(Table<?> name) {
        return new File(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public File where(Condition condition) {
        return new File(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public File where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public File where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public File where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public File where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public File where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public File where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public File where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public File whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public File whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
