/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared.tables;


import com.santika.simrs.jooq.shared.Keys;
import com.santika.simrs.jooq.shared.Shared;
import com.santika.simrs.jooq.shared.tables.Permissions.PermissionsPath;
import com.santika.simrs.jooq.shared.tables.Roles.RolesPath;
import com.santika.simrs.jooq.shared.tables.records.RoleHasPermissionRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoleHasPermission extends TableImpl<RoleHasPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SHARED.ROLE_HAS_PERMISSION</code>
     */
    public static final RoleHasPermission ROLE_HAS_PERMISSION = new RoleHasPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoleHasPermissionRecord> getRecordType() {
        return RoleHasPermissionRecord.class;
    }

    /**
     * The column <code>SHARED.ROLE_HAS_PERMISSION.ROLE_ID</code>.
     */
    public final TableField<RoleHasPermissionRecord, UUID> ROLE_ID = createField(DSL.name("ROLE_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>SHARED.ROLE_HAS_PERMISSION.PERMISSION_ID</code>.
     */
    public final TableField<RoleHasPermissionRecord, UUID> PERMISSION_ID = createField(DSL.name("PERMISSION_ID"), SQLDataType.UUID.nullable(false), this, "");

    private RoleHasPermission(Name alias, Table<RoleHasPermissionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RoleHasPermission(Name alias, Table<RoleHasPermissionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SHARED.ROLE_HAS_PERMISSION</code> table reference
     */
    public RoleHasPermission(String alias) {
        this(DSL.name(alias), ROLE_HAS_PERMISSION);
    }

    /**
     * Create an aliased <code>SHARED.ROLE_HAS_PERMISSION</code> table reference
     */
    public RoleHasPermission(Name alias) {
        this(alias, ROLE_HAS_PERMISSION);
    }

    /**
     * Create a <code>SHARED.ROLE_HAS_PERMISSION</code> table reference
     */
    public RoleHasPermission() {
        this(DSL.name("ROLE_HAS_PERMISSION"), null);
    }

    public <O extends Record> RoleHasPermission(Table<O> path, ForeignKey<O, RoleHasPermissionRecord> childPath, InverseForeignKey<O, RoleHasPermissionRecord> parentPath) {
        super(path, childPath, parentPath, ROLE_HAS_PERMISSION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RoleHasPermissionPath extends RoleHasPermission implements Path<RoleHasPermissionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RoleHasPermissionPath(Table<O> path, ForeignKey<O, RoleHasPermissionRecord> childPath, InverseForeignKey<O, RoleHasPermissionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RoleHasPermissionPath(Name alias, Table<RoleHasPermissionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RoleHasPermissionPath as(String alias) {
            return new RoleHasPermissionPath(DSL.name(alias), this);
        }

        @Override
        public RoleHasPermissionPath as(Name alias) {
            return new RoleHasPermissionPath(alias, this);
        }

        @Override
        public RoleHasPermissionPath as(Table<?> alias) {
            return new RoleHasPermissionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Shared.SHARED;
    }

    @Override
    public UniqueKey<RoleHasPermissionRecord> getPrimaryKey() {
        return Keys.PK_ROLE_HAS_PERMISSION;
    }

    @Override
    public List<ForeignKey<RoleHasPermissionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_RHP_PERMISSION_ID, Keys.FK_RHP_ROLE_ID);
    }

    private transient PermissionsPath _permissions;

    /**
     * Get the implicit join path to the <code>SHARED.PERMISSIONS</code> table.
     */
    public PermissionsPath permissions() {
        if (_permissions == null)
            _permissions = new PermissionsPath(this, Keys.FK_RHP_PERMISSION_ID, null);

        return _permissions;
    }

    private transient RolesPath _roles;

    /**
     * Get the implicit join path to the <code>SHARED.ROLES</code> table.
     */
    public RolesPath roles() {
        if (_roles == null)
            _roles = new RolesPath(this, Keys.FK_RHP_ROLE_ID, null);

        return _roles;
    }

    @Override
    public RoleHasPermission as(String alias) {
        return new RoleHasPermission(DSL.name(alias), this);
    }

    @Override
    public RoleHasPermission as(Name alias) {
        return new RoleHasPermission(alias, this);
    }

    @Override
    public RoleHasPermission as(Table<?> alias) {
        return new RoleHasPermission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleHasPermission rename(String name) {
        return new RoleHasPermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleHasPermission rename(Name name) {
        return new RoleHasPermission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleHasPermission rename(Table<?> name) {
        return new RoleHasPermission(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoleHasPermission where(Condition condition) {
        return new RoleHasPermission(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoleHasPermission where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoleHasPermission where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoleHasPermission where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoleHasPermission where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoleHasPermission where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoleHasPermission where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoleHasPermission where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoleHasPermission whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoleHasPermission whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
