/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared.tables;


import com.santika.simrs.jooq.shared.Indexes;
import com.santika.simrs.jooq.shared.Keys;
import com.santika.simrs.jooq.shared.Shared;
import com.santika.simrs.jooq.shared.tables.Users.UsersPath;
import com.santika.simrs.jooq.shared.tables.records.StorageFilesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StorageFiles extends TableImpl<StorageFilesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SHARED.STORAGE_FILES</code>
     */
    public static final StorageFiles STORAGE_FILES = new StorageFiles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StorageFilesRecord> getRecordType() {
        return StorageFilesRecord.class;
    }

    /**
     * The column <code>SHARED.STORAGE_FILES.ID</code>.
     */
    public final TableField<StorageFilesRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>SHARED.STORAGE_FILES.ORIGINAL_NAME</code>.
     */
    public final TableField<StorageFilesRecord, String> ORIGINAL_NAME = createField(DSL.name("ORIGINAL_NAME"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>SHARED.STORAGE_FILES.STORED_NAME</code>.
     */
    public final TableField<StorageFilesRecord, String> STORED_NAME = createField(DSL.name("STORED_NAME"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>SHARED.STORAGE_FILES.PATH</code>.
     */
    public final TableField<StorageFilesRecord, String> PATH = createField(DSL.name("PATH"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>SHARED.STORAGE_FILES.EXT</code>.
     */
    public final TableField<StorageFilesRecord, String> EXT = createField(DSL.name("EXT"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>SHARED.STORAGE_FILES.SIZE</code>.
     */
    public final TableField<StorageFilesRecord, Long> SIZE = createField(DSL.name("SIZE"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>SHARED.STORAGE_FILES.MIME_TYPE</code>.
     */
    public final TableField<StorageFilesRecord, String> MIME_TYPE = createField(DSL.name("MIME_TYPE"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>SHARED.STORAGE_FILES.MODULE</code>.
     */
    public final TableField<StorageFilesRecord, String> MODULE = createField(DSL.name("MODULE"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>SHARED.STORAGE_FILES.ENTITY_ID</code>.
     */
    public final TableField<StorageFilesRecord, UUID> ENTITY_ID = createField(DSL.name("ENTITY_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>SHARED.STORAGE_FILES.UPLOADED_BY</code>.
     */
    public final TableField<StorageFilesRecord, UUID> UPLOADED_BY = createField(DSL.name("UPLOADED_BY"), SQLDataType.UUID, this, "");

    /**
     * The column <code>SHARED.STORAGE_FILES.MOVED_FROM_TEMP_ID</code>.
     */
    public final TableField<StorageFilesRecord, UUID> MOVED_FROM_TEMP_ID = createField(DSL.name("MOVED_FROM_TEMP_ID"), SQLDataType.UUID, this, "");

    /**
     * The column <code>SHARED.STORAGE_FILES.VERSION</code>.
     */
    public final TableField<StorageFilesRecord, Long> VERSION = createField(DSL.name("VERSION"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>SHARED.STORAGE_FILES.CREATED_AT</code>.
     */
    public final TableField<StorageFilesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>SHARED.STORAGE_FILES.UPDATED_AT</code>.
     */
    public final TableField<StorageFilesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>SHARED.STORAGE_FILES.DELETED_AT</code>.
     */
    public final TableField<StorageFilesRecord, LocalDateTime> DELETED_AT = createField(DSL.name("DELETED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private StorageFiles(Name alias, Table<StorageFilesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private StorageFiles(Name alias, Table<StorageFilesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SHARED.STORAGE_FILES</code> table reference
     */
    public StorageFiles(String alias) {
        this(DSL.name(alias), STORAGE_FILES);
    }

    /**
     * Create an aliased <code>SHARED.STORAGE_FILES</code> table reference
     */
    public StorageFiles(Name alias) {
        this(alias, STORAGE_FILES);
    }

    /**
     * Create a <code>SHARED.STORAGE_FILES</code> table reference
     */
    public StorageFiles() {
        this(DSL.name("STORAGE_FILES"), null);
    }

    public <O extends Record> StorageFiles(Table<O> path, ForeignKey<O, StorageFilesRecord> childPath, InverseForeignKey<O, StorageFilesRecord> parentPath) {
        super(path, childPath, parentPath, STORAGE_FILES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class StorageFilesPath extends StorageFiles implements Path<StorageFilesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> StorageFilesPath(Table<O> path, ForeignKey<O, StorageFilesRecord> childPath, InverseForeignKey<O, StorageFilesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private StorageFilesPath(Name alias, Table<StorageFilesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public StorageFilesPath as(String alias) {
            return new StorageFilesPath(DSL.name(alias), this);
        }

        @Override
        public StorageFilesPath as(Name alias) {
            return new StorageFilesPath(alias, this);
        }

        @Override
        public StorageFilesPath as(Table<?> alias) {
            return new StorageFilesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Shared.SHARED;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_STORAGE_FILES_DELETED_AT, Indexes.IDX_STORAGE_FILES_MODULE_ENTITY, Indexes.IDX_STORAGE_FILES_UPLOADED_BY);
    }

    @Override
    public UniqueKey<StorageFilesRecord> getPrimaryKey() {
        return Keys.PK_STORAGE_FILES;
    }

    @Override
    public List<ForeignKey<StorageFilesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_STORAGE_FILES_UPLOADED_BY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>SHARED.USERS</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.FK_STORAGE_FILES_UPLOADED_BY, null);

        return _users;
    }

    @Override
    public StorageFiles as(String alias) {
        return new StorageFiles(DSL.name(alias), this);
    }

    @Override
    public StorageFiles as(Name alias) {
        return new StorageFiles(alias, this);
    }

    @Override
    public StorageFiles as(Table<?> alias) {
        return new StorageFiles(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StorageFiles rename(String name) {
        return new StorageFiles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StorageFiles rename(Name name) {
        return new StorageFiles(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StorageFiles rename(Table<?> name) {
        return new StorageFiles(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StorageFiles where(Condition condition) {
        return new StorageFiles(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StorageFiles where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StorageFiles where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StorageFiles where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StorageFiles where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StorageFiles where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StorageFiles where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StorageFiles where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StorageFiles whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StorageFiles whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
