/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared.tables;


import com.santika.simrs.jooq.shared.Indexes;
import com.santika.simrs.jooq.shared.Keys;
import com.santika.simrs.jooq.shared.Shared;
import com.santika.simrs.jooq.shared.tables.Users.UsersPath;
import com.santika.simrs.jooq.shared.tables.records.TempFilesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TempFiles extends TableImpl<TempFilesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SHARED.TEMP_FILES</code>
     */
    public static final TempFiles TEMP_FILES = new TempFiles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TempFilesRecord> getRecordType() {
        return TempFilesRecord.class;
    }

    /**
     * The column <code>SHARED.TEMP_FILES.ID</code>.
     */
    public final TableField<TempFilesRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>SHARED.TEMP_FILES.ORIGINAL_NAME</code>.
     */
    public final TableField<TempFilesRecord, String> ORIGINAL_NAME = createField(DSL.name("ORIGINAL_NAME"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>SHARED.TEMP_FILES.STORED_NAME</code>.
     */
    public final TableField<TempFilesRecord, String> STORED_NAME = createField(DSL.name("STORED_NAME"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>SHARED.TEMP_FILES.PATH</code>.
     */
    public final TableField<TempFilesRecord, String> PATH = createField(DSL.name("PATH"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>SHARED.TEMP_FILES.EXT</code>.
     */
    public final TableField<TempFilesRecord, String> EXT = createField(DSL.name("EXT"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>SHARED.TEMP_FILES.SIZE</code>.
     */
    public final TableField<TempFilesRecord, Long> SIZE = createField(DSL.name("SIZE"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>SHARED.TEMP_FILES.MIME_TYPE</code>.
     */
    public final TableField<TempFilesRecord, String> MIME_TYPE = createField(DSL.name("MIME_TYPE"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>SHARED.TEMP_FILES.UPLOAD_TOKEN</code>.
     */
    public final TableField<TempFilesRecord, String> UPLOAD_TOKEN = createField(DSL.name("UPLOAD_TOKEN"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>SHARED.TEMP_FILES.UPLOADED_BY</code>.
     */
    public final TableField<TempFilesRecord, UUID> UPLOADED_BY = createField(DSL.name("UPLOADED_BY"), SQLDataType.UUID, this, "");

    /**
     * The column <code>SHARED.TEMP_FILES.EXPIRES_AT</code>.
     */
    public final TableField<TempFilesRecord, LocalDateTime> EXPIRES_AT = createField(DSL.name("EXPIRES_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>SHARED.TEMP_FILES.CREATED_AT</code>.
     */
    public final TableField<TempFilesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>SHARED.TEMP_FILES.UPDATED_AT</code>.
     */
    public final TableField<TempFilesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private TempFiles(Name alias, Table<TempFilesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TempFiles(Name alias, Table<TempFilesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SHARED.TEMP_FILES</code> table reference
     */
    public TempFiles(String alias) {
        this(DSL.name(alias), TEMP_FILES);
    }

    /**
     * Create an aliased <code>SHARED.TEMP_FILES</code> table reference
     */
    public TempFiles(Name alias) {
        this(alias, TEMP_FILES);
    }

    /**
     * Create a <code>SHARED.TEMP_FILES</code> table reference
     */
    public TempFiles() {
        this(DSL.name("TEMP_FILES"), null);
    }

    public <O extends Record> TempFiles(Table<O> path, ForeignKey<O, TempFilesRecord> childPath, InverseForeignKey<O, TempFilesRecord> parentPath) {
        super(path, childPath, parentPath, TEMP_FILES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TempFilesPath extends TempFiles implements Path<TempFilesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TempFilesPath(Table<O> path, ForeignKey<O, TempFilesRecord> childPath, InverseForeignKey<O, TempFilesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TempFilesPath(Name alias, Table<TempFilesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TempFilesPath as(String alias) {
            return new TempFilesPath(DSL.name(alias), this);
        }

        @Override
        public TempFilesPath as(Name alias) {
            return new TempFilesPath(alias, this);
        }

        @Override
        public TempFilesPath as(Table<?> alias) {
            return new TempFilesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Shared.SHARED;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_TEMP_FILES_EXPIRES_AT, Indexes.IDX_TEMP_FILES_UPLOAD_TOKEN, Indexes.IDX_TEMP_FILES_UPLOADED_BY);
    }

    @Override
    public UniqueKey<TempFilesRecord> getPrimaryKey() {
        return Keys.PK_TEMP_FILES;
    }

    @Override
    public List<UniqueKey<TempFilesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_8);
    }

    @Override
    public List<ForeignKey<TempFilesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_TEMP_FILES_UPLOADED_BY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>SHARED.USERS</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.FK_TEMP_FILES_UPLOADED_BY, null);

        return _users;
    }

    @Override
    public TempFiles as(String alias) {
        return new TempFiles(DSL.name(alias), this);
    }

    @Override
    public TempFiles as(Name alias) {
        return new TempFiles(alias, this);
    }

    @Override
    public TempFiles as(Table<?> alias) {
        return new TempFiles(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TempFiles rename(String name) {
        return new TempFiles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TempFiles rename(Name name) {
        return new TempFiles(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TempFiles rename(Table<?> name) {
        return new TempFiles(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TempFiles where(Condition condition) {
        return new TempFiles(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TempFiles where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TempFiles where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TempFiles where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TempFiles where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TempFiles where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TempFiles where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TempFiles where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TempFiles whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TempFiles whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
