/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared.tables;


import com.santika.simrs.jooq.shared.Keys;
import com.santika.simrs.jooq.shared.Shared;
import com.santika.simrs.jooq.shared.tables.Roles.RolesPath;
import com.santika.simrs.jooq.shared.tables.Users.UsersPath;
import com.santika.simrs.jooq.shared.tables.records.UserHasRoleRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserHasRole extends TableImpl<UserHasRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SHARED.USER_HAS_ROLE</code>
     */
    public static final UserHasRole USER_HAS_ROLE = new UserHasRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserHasRoleRecord> getRecordType() {
        return UserHasRoleRecord.class;
    }

    /**
     * The column <code>SHARED.USER_HAS_ROLE.USER_ID</code>.
     */
    public final TableField<UserHasRoleRecord, UUID> USER_ID = createField(DSL.name("USER_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>SHARED.USER_HAS_ROLE.ROLE_ID</code>.
     */
    public final TableField<UserHasRoleRecord, UUID> ROLE_ID = createField(DSL.name("ROLE_ID"), SQLDataType.UUID.nullable(false), this, "");

    private UserHasRole(Name alias, Table<UserHasRoleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserHasRole(Name alias, Table<UserHasRoleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SHARED.USER_HAS_ROLE</code> table reference
     */
    public UserHasRole(String alias) {
        this(DSL.name(alias), USER_HAS_ROLE);
    }

    /**
     * Create an aliased <code>SHARED.USER_HAS_ROLE</code> table reference
     */
    public UserHasRole(Name alias) {
        this(alias, USER_HAS_ROLE);
    }

    /**
     * Create a <code>SHARED.USER_HAS_ROLE</code> table reference
     */
    public UserHasRole() {
        this(DSL.name("USER_HAS_ROLE"), null);
    }

    public <O extends Record> UserHasRole(Table<O> path, ForeignKey<O, UserHasRoleRecord> childPath, InverseForeignKey<O, UserHasRoleRecord> parentPath) {
        super(path, childPath, parentPath, USER_HAS_ROLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserHasRolePath extends UserHasRole implements Path<UserHasRoleRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserHasRolePath(Table<O> path, ForeignKey<O, UserHasRoleRecord> childPath, InverseForeignKey<O, UserHasRoleRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserHasRolePath(Name alias, Table<UserHasRoleRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserHasRolePath as(String alias) {
            return new UserHasRolePath(DSL.name(alias), this);
        }

        @Override
        public UserHasRolePath as(Name alias) {
            return new UserHasRolePath(alias, this);
        }

        @Override
        public UserHasRolePath as(Table<?> alias) {
            return new UserHasRolePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Shared.SHARED;
    }

    @Override
    public UniqueKey<UserHasRoleRecord> getPrimaryKey() {
        return Keys.PK_USER_HAS_ROLE;
    }

    @Override
    public List<ForeignKey<UserHasRoleRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_UHR_ROLE_ID, Keys.FK_UHR_USER_ID);
    }

    private transient RolesPath _roles;

    /**
     * Get the implicit join path to the <code>SHARED.ROLES</code> table.
     */
    public RolesPath roles() {
        if (_roles == null)
            _roles = new RolesPath(this, Keys.FK_UHR_ROLE_ID, null);

        return _roles;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>SHARED.USERS</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.FK_UHR_USER_ID, null);

        return _users;
    }

    @Override
    public UserHasRole as(String alias) {
        return new UserHasRole(DSL.name(alias), this);
    }

    @Override
    public UserHasRole as(Name alias) {
        return new UserHasRole(alias, this);
    }

    @Override
    public UserHasRole as(Table<?> alias) {
        return new UserHasRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserHasRole rename(String name) {
        return new UserHasRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserHasRole rename(Name name) {
        return new UserHasRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserHasRole rename(Table<?> name) {
        return new UserHasRole(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserHasRole where(Condition condition) {
        return new UserHasRole(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserHasRole where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserHasRole where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserHasRole where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserHasRole where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserHasRole where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserHasRole where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserHasRole where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserHasRole whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserHasRole whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
