/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared.tables;


import com.santika.simrs.jooq.shared.Indexes;
import com.santika.simrs.jooq.shared.Keys;
import com.santika.simrs.jooq.shared.Shared;
import com.santika.simrs.jooq.shared.tables.Users.UsersPath;
import com.santika.simrs.jooq.shared.tables.records.UserSessionsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserSessions extends TableImpl<UserSessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SHARED.USER_SESSIONS</code>
     */
    public static final UserSessions USER_SESSIONS = new UserSessions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserSessionsRecord> getRecordType() {
        return UserSessionsRecord.class;
    }

    /**
     * The column <code>SHARED.USER_SESSIONS.ID</code>.
     */
    public final TableField<UserSessionsRecord, UUID> ID = createField(DSL.name("ID"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("\"PUBLIC\".\"GEN_RANDOM_UUID\"()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>SHARED.USER_SESSIONS.USER_ID</code>.
     */
    public final TableField<UserSessionsRecord, UUID> USER_ID = createField(DSL.name("USER_ID"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>SHARED.USER_SESSIONS.JTI</code>.
     */
    public final TableField<UserSessionsRecord, UUID> JTI = createField(DSL.name("JTI"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>SHARED.USER_SESSIONS.DEVICE_INFO</code>.
     */
    public final TableField<UserSessionsRecord, String> DEVICE_INFO = createField(DSL.name("DEVICE_INFO"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>SHARED.USER_SESSIONS.IP_ADDRESS</code>.
     */
    public final TableField<UserSessionsRecord, String> IP_ADDRESS = createField(DSL.name("IP_ADDRESS"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>SHARED.USER_SESSIONS.USER_AGENT</code>.
     */
    public final TableField<UserSessionsRecord, String> USER_AGENT = createField(DSL.name("USER_AGENT"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>SHARED.USER_SESSIONS.REVOKED_AT</code>.
     */
    public final TableField<UserSessionsRecord, LocalDateTime> REVOKED_AT = createField(DSL.name("REVOKED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>SHARED.USER_SESSIONS.REVOKED_REASON</code>.
     */
    public final TableField<UserSessionsRecord, String> REVOKED_REASON = createField(DSL.name("REVOKED_REASON"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>SHARED.USER_SESSIONS.CREATED_AT</code>.
     */
    public final TableField<UserSessionsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>SHARED.USER_SESSIONS.LAST_USED_AT</code>.
     */
    public final TableField<UserSessionsRecord, LocalDateTime> LAST_USED_AT = createField(DSL.name("LAST_USED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>SHARED.USER_SESSIONS.EXPIRES_AT</code>.
     */
    public final TableField<UserSessionsRecord, LocalDateTime> EXPIRES_AT = createField(DSL.name("EXPIRES_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private UserSessions(Name alias, Table<UserSessionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserSessions(Name alias, Table<UserSessionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>SHARED.USER_SESSIONS</code> table reference
     */
    public UserSessions(String alias) {
        this(DSL.name(alias), USER_SESSIONS);
    }

    /**
     * Create an aliased <code>SHARED.USER_SESSIONS</code> table reference
     */
    public UserSessions(Name alias) {
        this(alias, USER_SESSIONS);
    }

    /**
     * Create a <code>SHARED.USER_SESSIONS</code> table reference
     */
    public UserSessions() {
        this(DSL.name("USER_SESSIONS"), null);
    }

    public <O extends Record> UserSessions(Table<O> path, ForeignKey<O, UserSessionsRecord> childPath, InverseForeignKey<O, UserSessionsRecord> parentPath) {
        super(path, childPath, parentPath, USER_SESSIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserSessionsPath extends UserSessions implements Path<UserSessionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserSessionsPath(Table<O> path, ForeignKey<O, UserSessionsRecord> childPath, InverseForeignKey<O, UserSessionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserSessionsPath(Name alias, Table<UserSessionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserSessionsPath as(String alias) {
            return new UserSessionsPath(DSL.name(alias), this);
        }

        @Override
        public UserSessionsPath as(Name alias) {
            return new UserSessionsPath(alias, this);
        }

        @Override
        public UserSessionsPath as(Table<?> alias) {
            return new UserSessionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Shared.SHARED;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_USER_SESSIONS_USER_ID, Indexes.UQ_USER_SESSIONS_JTI);
    }

    @Override
    public UniqueKey<UserSessionsRecord> getPrimaryKey() {
        return Keys.PK_USER_SESSIONS;
    }

    @Override
    public List<ForeignKey<UserSessionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_USER_SESSIONS_USER_ID);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>SHARED.USERS</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.FK_USER_SESSIONS_USER_ID, null);

        return _users;
    }

    @Override
    public UserSessions as(String alias) {
        return new UserSessions(DSL.name(alias), this);
    }

    @Override
    public UserSessions as(Name alias) {
        return new UserSessions(alias, this);
    }

    @Override
    public UserSessions as(Table<?> alias) {
        return new UserSessions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserSessions rename(String name) {
        return new UserSessions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserSessions rename(Name name) {
        return new UserSessions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserSessions rename(Table<?> name) {
        return new UserSessions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserSessions where(Condition condition) {
        return new UserSessions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserSessions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserSessions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserSessions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserSessions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserSessions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserSessions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserSessions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserSessions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserSessions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
