/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq;


import com.santika.simrs.jooq.kepegawaian.Kepegawaian;
import com.santika.simrs.jooq.master.Master;
import com.santika.simrs.jooq.shared.Shared;

import java.util.Arrays;
import java.util.List;

import org.jooq.Constants;
import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_CATALOG</code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>KEPEGAWAIAN</code>.
     */
    public final Kepegawaian KEPEGAWAIAN = Kepegawaian.KEPEGAWAIAN;

    /**
     * The schema <code>MASTER</code>.
     */
    public final Master MASTER = Master.MASTER;

    /**
     * The schema <code>SHARED</code>.
     */
    public final Shared SHARED = Shared.SHARED;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        return Arrays.asList(
            Kepegawaian.KEPEGAWAIAN,
            Master.MASTER,
            Shared.SHARED
        );
    }

    /**
     * A reference to the 3.19 minor release of the code generator. If this
     * doesn't compile, it's because the runtime library uses an older minor
     * release, namely: 3.19. You can turn off the generation of this reference
     * by specifying /configuration/generator/generate/jooqVersionReference
     */
    private static final String REQUIRE_RUNTIME_JOOQ_VERSION = Constants.VERSION_3_19;
}
