/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared.tables.records;


import com.santika.simrs.jooq.shared.tables.Audit;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuditRecord extends UpdatableRecordImpl<AuditRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SHARED.AUDIT.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>SHARED.AUDIT.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>SHARED.AUDIT.USERNAME</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SHARED.AUDIT.USERNAME</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SHARED.AUDIT.ACTION</code>.
     */
    public void setAction(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SHARED.AUDIT.ACTION</code>.
     */
    public String getAction() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SHARED.AUDIT.PAYLOAD</code>.
     */
    public void setPayload(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SHARED.AUDIT.PAYLOAD</code>.
     */
    public String getPayload() {
        return (String) get(3);
    }

    /**
     * Setter for <code>SHARED.AUDIT.TIMESTAMP</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>SHARED.AUDIT.TIMESTAMP</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuditRecord
     */
    public AuditRecord() {
        super(Audit.AUDIT);
    }

    /**
     * Create a detached, initialised AuditRecord
     */
    public AuditRecord(UUID id, String username, String action, String payload, LocalDateTime timestamp) {
        super(Audit.AUDIT);

        setId(id);
        setUsername(username);
        setAction(action);
        setPayload(payload);
        setTimestamp(timestamp);
        resetChangedOnNotNull();
    }
}
