/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared.tables.records;


import com.santika.simrs.jooq.shared.tables.File;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FileRecord extends UpdatableRecordImpl<FileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SHARED.FILE.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>SHARED.FILE.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>SHARED.FILE.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SHARED.FILE.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SHARED.FILE.PATH</code>.
     */
    public void setPath(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SHARED.FILE.PATH</code>.
     */
    public String getPath() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SHARED.FILE.SIZE</code>.
     */
    public void setSize(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SHARED.FILE.SIZE</code>.
     */
    public String getSize() {
        return (String) get(3);
    }

    /**
     * Setter for <code>SHARED.FILE.EXT</code>.
     */
    public void setExt(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>SHARED.FILE.EXT</code>.
     */
    public String getExt() {
        return (String) get(4);
    }

    /**
     * Setter for <code>SHARED.FILE.MIME_TYPE</code>.
     */
    public void setMimeType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>SHARED.FILE.MIME_TYPE</code>.
     */
    public String getMimeType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>SHARED.FILE.TEMP_NAME</code>.
     */
    public void setTempName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>SHARED.FILE.TEMP_NAME</code>.
     */
    public String getTempName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>SHARED.FILE.IS_TEMP</code>.
     */
    public void setIsTemp(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>SHARED.FILE.IS_TEMP</code>.
     */
    public Boolean getIsTemp() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>SHARED.FILE.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>SHARED.FILE.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>SHARED.FILE.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>SHARED.FILE.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>SHARED.FILE.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>SHARED.FILE.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileRecord
     */
    public FileRecord() {
        super(File.FILE);
    }

    /**
     * Create a detached, initialised FileRecord
     */
    public FileRecord(UUID id, String name, String path, String size, String ext, String mimeType, String tempName, Boolean isTemp, LocalDateTime deletedAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(File.FILE);

        setId(id);
        setName(name);
        setPath(path);
        setSize(size);
        setExt(ext);
        setMimeType(mimeType);
        setTempName(tempName);
        setIsTemp(isTemp);
        setDeletedAt(deletedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
