/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared.tables.records;


import com.santika.simrs.jooq.shared.tables.RoleHasPermission;

import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoleHasPermissionRecord extends UpdatableRecordImpl<RoleHasPermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SHARED.ROLE_HAS_PERMISSION.ROLE_ID</code>.
     */
    public void setRoleId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>SHARED.ROLE_HAS_PERMISSION.ROLE_ID</code>.
     */
    public UUID getRoleId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>SHARED.ROLE_HAS_PERMISSION.PERMISSION_ID</code>.
     */
    public void setPermissionId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>SHARED.ROLE_HAS_PERMISSION.PERMISSION_ID</code>.
     */
    public UUID getPermissionId() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleHasPermissionRecord
     */
    public RoleHasPermissionRecord() {
        super(RoleHasPermission.ROLE_HAS_PERMISSION);
    }

    /**
     * Create a detached, initialised RoleHasPermissionRecord
     */
    public RoleHasPermissionRecord(UUID roleId, UUID permissionId) {
        super(RoleHasPermission.ROLE_HAS_PERMISSION);

        setRoleId(roleId);
        setPermissionId(permissionId);
        resetChangedOnNotNull();
    }
}
