/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared.tables.records;


import com.santika.simrs.jooq.shared.tables.StorageFiles;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StorageFilesRecord extends UpdatableRecordImpl<StorageFilesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SHARED.STORAGE_FILES.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>SHARED.STORAGE_FILES.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>SHARED.STORAGE_FILES.ORIGINAL_NAME</code>.
     */
    public void setOriginalName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SHARED.STORAGE_FILES.ORIGINAL_NAME</code>.
     */
    public String getOriginalName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SHARED.STORAGE_FILES.STORED_NAME</code>.
     */
    public void setStoredName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SHARED.STORAGE_FILES.STORED_NAME</code>.
     */
    public String getStoredName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SHARED.STORAGE_FILES.PATH</code>.
     */
    public void setPath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SHARED.STORAGE_FILES.PATH</code>.
     */
    public String getPath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>SHARED.STORAGE_FILES.EXT</code>.
     */
    public void setExt(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>SHARED.STORAGE_FILES.EXT</code>.
     */
    public String getExt() {
        return (String) get(4);
    }

    /**
     * Setter for <code>SHARED.STORAGE_FILES.SIZE</code>.
     */
    public void setSize(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>SHARED.STORAGE_FILES.SIZE</code>.
     */
    public Long getSize() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>SHARED.STORAGE_FILES.MIME_TYPE</code>.
     */
    public void setMimeType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>SHARED.STORAGE_FILES.MIME_TYPE</code>.
     */
    public String getMimeType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>SHARED.STORAGE_FILES.MODULE</code>.
     */
    public void setModule(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>SHARED.STORAGE_FILES.MODULE</code>.
     */
    public String getModule() {
        return (String) get(7);
    }

    /**
     * Setter for <code>SHARED.STORAGE_FILES.ENTITY_ID</code>.
     */
    public void setEntityId(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>SHARED.STORAGE_FILES.ENTITY_ID</code>.
     */
    public UUID getEntityId() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>SHARED.STORAGE_FILES.UPLOADED_BY</code>.
     */
    public void setUploadedBy(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>SHARED.STORAGE_FILES.UPLOADED_BY</code>.
     */
    public UUID getUploadedBy() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>SHARED.STORAGE_FILES.MOVED_FROM_TEMP_ID</code>.
     */
    public void setMovedFromTempId(UUID value) {
        set(10, value);
    }

    /**
     * Getter for <code>SHARED.STORAGE_FILES.MOVED_FROM_TEMP_ID</code>.
     */
    public UUID getMovedFromTempId() {
        return (UUID) get(10);
    }

    /**
     * Setter for <code>SHARED.STORAGE_FILES.VERSION</code>.
     */
    public void setVersion(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>SHARED.STORAGE_FILES.VERSION</code>.
     */
    public Long getVersion() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>SHARED.STORAGE_FILES.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>SHARED.STORAGE_FILES.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>SHARED.STORAGE_FILES.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>SHARED.STORAGE_FILES.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>SHARED.STORAGE_FILES.DELETED_AT</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>SHARED.STORAGE_FILES.DELETED_AT</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StorageFilesRecord
     */
    public StorageFilesRecord() {
        super(StorageFiles.STORAGE_FILES);
    }

    /**
     * Create a detached, initialised StorageFilesRecord
     */
    public StorageFilesRecord(UUID id, String originalName, String storedName, String path, String ext, Long size, String mimeType, String module, UUID entityId, UUID uploadedBy, UUID movedFromTempId, Long version, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt) {
        super(StorageFiles.STORAGE_FILES);

        setId(id);
        setOriginalName(originalName);
        setStoredName(storedName);
        setPath(path);
        setExt(ext);
        setSize(size);
        setMimeType(mimeType);
        setModule(module);
        setEntityId(entityId);
        setUploadedBy(uploadedBy);
        setMovedFromTempId(movedFromTempId);
        setVersion(version);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetChangedOnNotNull();
    }
}
