/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared.tables.records;


import com.santika.simrs.jooq.shared.tables.TempFiles;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TempFilesRecord extends UpdatableRecordImpl<TempFilesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SHARED.TEMP_FILES.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>SHARED.TEMP_FILES.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>SHARED.TEMP_FILES.ORIGINAL_NAME</code>.
     */
    public void setOriginalName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SHARED.TEMP_FILES.ORIGINAL_NAME</code>.
     */
    public String getOriginalName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SHARED.TEMP_FILES.STORED_NAME</code>.
     */
    public void setStoredName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SHARED.TEMP_FILES.STORED_NAME</code>.
     */
    public String getStoredName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SHARED.TEMP_FILES.PATH</code>.
     */
    public void setPath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SHARED.TEMP_FILES.PATH</code>.
     */
    public String getPath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>SHARED.TEMP_FILES.EXT</code>.
     */
    public void setExt(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>SHARED.TEMP_FILES.EXT</code>.
     */
    public String getExt() {
        return (String) get(4);
    }

    /**
     * Setter for <code>SHARED.TEMP_FILES.SIZE</code>.
     */
    public void setSize(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>SHARED.TEMP_FILES.SIZE</code>.
     */
    public Long getSize() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>SHARED.TEMP_FILES.MIME_TYPE</code>.
     */
    public void setMimeType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>SHARED.TEMP_FILES.MIME_TYPE</code>.
     */
    public String getMimeType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>SHARED.TEMP_FILES.UPLOAD_TOKEN</code>.
     */
    public void setUploadToken(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>SHARED.TEMP_FILES.UPLOAD_TOKEN</code>.
     */
    public String getUploadToken() {
        return (String) get(7);
    }

    /**
     * Setter for <code>SHARED.TEMP_FILES.UPLOADED_BY</code>.
     */
    public void setUploadedBy(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>SHARED.TEMP_FILES.UPLOADED_BY</code>.
     */
    public UUID getUploadedBy() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>SHARED.TEMP_FILES.EXPIRES_AT</code>.
     */
    public void setExpiresAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>SHARED.TEMP_FILES.EXPIRES_AT</code>.
     */
    public LocalDateTime getExpiresAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>SHARED.TEMP_FILES.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>SHARED.TEMP_FILES.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>SHARED.TEMP_FILES.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>SHARED.TEMP_FILES.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TempFilesRecord
     */
    public TempFilesRecord() {
        super(TempFiles.TEMP_FILES);
    }

    /**
     * Create a detached, initialised TempFilesRecord
     */
    public TempFilesRecord(UUID id, String originalName, String storedName, String path, String ext, Long size, String mimeType, String uploadToken, UUID uploadedBy, LocalDateTime expiresAt, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(TempFiles.TEMP_FILES);

        setId(id);
        setOriginalName(originalName);
        setStoredName(storedName);
        setPath(path);
        setExt(ext);
        setSize(size);
        setMimeType(mimeType);
        setUploadToken(uploadToken);
        setUploadedBy(uploadedBy);
        setExpiresAt(expiresAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
