/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared.tables.records;


import com.santika.simrs.jooq.shared.tables.UserHasRole;

import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserHasRoleRecord extends UpdatableRecordImpl<UserHasRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SHARED.USER_HAS_ROLE.USER_ID</code>.
     */
    public void setUserId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>SHARED.USER_HAS_ROLE.USER_ID</code>.
     */
    public UUID getUserId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>SHARED.USER_HAS_ROLE.ROLE_ID</code>.
     */
    public void setRoleId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>SHARED.USER_HAS_ROLE.ROLE_ID</code>.
     */
    public UUID getRoleId() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserHasRoleRecord
     */
    public UserHasRoleRecord() {
        super(UserHasRole.USER_HAS_ROLE);
    }

    /**
     * Create a detached, initialised UserHasRoleRecord
     */
    public UserHasRoleRecord(UUID userId, UUID roleId) {
        super(UserHasRole.USER_HAS_ROLE);

        setUserId(userId);
        setRoleId(roleId);
        resetChangedOnNotNull();
    }
}
