/*
 * This file is generated by jOOQ.
 */
package com.santika.simrs.jooq.shared.tables.records;


import com.santika.simrs.jooq.shared.tables.UserSessions;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserSessionsRecord extends UpdatableRecordImpl<UserSessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SHARED.USER_SESSIONS.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>SHARED.USER_SESSIONS.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>SHARED.USER_SESSIONS.USER_ID</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>SHARED.USER_SESSIONS.USER_ID</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>SHARED.USER_SESSIONS.JTI</code>.
     */
    public void setJti(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>SHARED.USER_SESSIONS.JTI</code>.
     */
    public UUID getJti() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>SHARED.USER_SESSIONS.DEVICE_INFO</code>.
     */
    public void setDeviceInfo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SHARED.USER_SESSIONS.DEVICE_INFO</code>.
     */
    public String getDeviceInfo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>SHARED.USER_SESSIONS.IP_ADDRESS</code>.
     */
    public void setIpAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>SHARED.USER_SESSIONS.IP_ADDRESS</code>.
     */
    public String getIpAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>SHARED.USER_SESSIONS.USER_AGENT</code>.
     */
    public void setUserAgent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>SHARED.USER_SESSIONS.USER_AGENT</code>.
     */
    public String getUserAgent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>SHARED.USER_SESSIONS.REVOKED_AT</code>.
     */
    public void setRevokedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>SHARED.USER_SESSIONS.REVOKED_AT</code>.
     */
    public LocalDateTime getRevokedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>SHARED.USER_SESSIONS.REVOKED_REASON</code>.
     */
    public void setRevokedReason(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>SHARED.USER_SESSIONS.REVOKED_REASON</code>.
     */
    public String getRevokedReason() {
        return (String) get(7);
    }

    /**
     * Setter for <code>SHARED.USER_SESSIONS.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>SHARED.USER_SESSIONS.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>SHARED.USER_SESSIONS.LAST_USED_AT</code>.
     */
    public void setLastUsedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>SHARED.USER_SESSIONS.LAST_USED_AT</code>.
     */
    public LocalDateTime getLastUsedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>SHARED.USER_SESSIONS.EXPIRES_AT</code>.
     */
    public void setExpiresAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>SHARED.USER_SESSIONS.EXPIRES_AT</code>.
     */
    public LocalDateTime getExpiresAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserSessionsRecord
     */
    public UserSessionsRecord() {
        super(UserSessions.USER_SESSIONS);
    }

    /**
     * Create a detached, initialised UserSessionsRecord
     */
    public UserSessionsRecord(UUID id, UUID userId, UUID jti, String deviceInfo, String ipAddress, String userAgent, LocalDateTime revokedAt, String revokedReason, LocalDateTime createdAt, LocalDateTime lastUsedAt, LocalDateTime expiresAt) {
        super(UserSessions.USER_SESSIONS);

        setId(id);
        setUserId(userId);
        setJti(jti);
        setDeviceInfo(deviceInfo);
        setIpAddress(ipAddress);
        setUserAgent(userAgent);
        setRevokedAt(revokedAt);
        setRevokedReason(revokedReason);
        setCreatedAt(createdAt);
        setLastUsedAt(lastUsedAt);
        setExpiresAt(expiresAt);
        resetChangedOnNotNull();
    }
}
